//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: owner/visit_controller.go:20

package spicegen

import (
	fmt "fmt"

	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct6bd173f54d1a performs the direct construction selected for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|15:VisitController.
func Construct6bd173f54d1a(dependency0 owner.Repository, dependency1 *i18n.Catalog) (*owner.VisitController, spicelifecycle.Cleanup, error) {
	value, err := owner.NewVisitController(dependency0, dependency1)
	if err != nil {
		var zero *owner.VisitController
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|15:VisitController (*github.com/StevenBuglione/spice/examples/petclinic/owner.VisitController): %w", err)
	}
	return value, nil, nil
}
