// Code generated by Spice. DO NOT EDIT.
// Source: postgres/owner_repository.go:17
//go:build !spice_generate

package postgres

import (
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
)

// spiceImplements55b41c6d3e05 verifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository.
var spiceImplements55b41c6d3e05 owner.Repository = *new(*OwnerRepository)
