// Code generated by Spice. DO NOT EDIT.
// Source: postgres/pet_type_repository.go:15
//go:build !spice_generate

package postgres

import (
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
)

// spiceImplementsce8e4c99400e verifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository.
var spiceImplementsce8e4c99400e owner.PetTypeRepository = *new(*PetTypeRepository)
