package postgres

// schemaSQL follows the canonical Spring Petclinic PostgreSQL schema while
// strengthening required domain columns with explicit NOT NULL constraints.
const schemaSQL = `CREATE TABLE IF NOT EXISTS vets (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name text NOT NULL,
	last_name text NOT NULL
);
CREATE INDEX IF NOT EXISTS vets_last_name_idx ON vets (last_name);

CREATE TABLE IF NOT EXISTS specialties (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS specialties_name_idx ON specialties (name);

CREATE TABLE IF NOT EXISTS vet_specialties (
	vet_id bigint NOT NULL REFERENCES vets (id),
	specialty_id bigint NOT NULL REFERENCES specialties (id),
	UNIQUE (vet_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS types (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL UNIQUE
);
CREATE INDEX IF NOT EXISTS types_name_idx ON types (name);

CREATE TABLE IF NOT EXISTS owners (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name text NOT NULL,
	last_name text NOT NULL,
	address text NOT NULL,
	city text NOT NULL,
	telephone text NOT NULL
);
CREATE INDEX IF NOT EXISTS owners_last_name_idx ON owners (last_name);

CREATE TABLE IF NOT EXISTS pets (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text NOT NULL,
	birth_date date NOT NULL,
	type_id bigint NOT NULL REFERENCES types (id),
	owner_id bigint NOT NULL REFERENCES owners (id)
);
CREATE INDEX IF NOT EXISTS pets_name_idx ON pets (name);
CREATE INDEX IF NOT EXISTS pets_owner_id_idx ON pets (owner_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_owner_pet_name
	ON pets (owner_id, lower(name));

CREATE TABLE IF NOT EXISTS visits (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pet_id bigint NOT NULL REFERENCES pets (id),
	visit_date date NOT NULL,
	description text NOT NULL
);
CREATE INDEX IF NOT EXISTS visits_pet_id_idx ON visits (pet_id);`

// seedSQL preserves the canonical Spring Petclinic reference identities and
// data. Conflict handling makes the migration retry-safe.
const seedSQL = `INSERT INTO vets (id, first_name, last_name) VALUES
	(1, 'James', 'Carter'),
	(2, 'Helen', 'Leary'),
	(3, 'Linda', 'Douglas'),
	(4, 'Rafael', 'Ortega'),
	(5, 'Henry', 'Stevens'),
	(6, 'Sharon', 'Jenkins')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('vets', 'id'), greatest((SELECT max(id) FROM vets), 1));

INSERT INTO specialties (id, name) VALUES
	(1, 'radiology'),
	(2, 'surgery'),
	(3, 'dentistry')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('specialties', 'id'), greatest((SELECT max(id) FROM specialties), 1));

INSERT INTO vet_specialties (vet_id, specialty_id) VALUES
	(2, 1),
	(3, 2),
	(3, 3),
	(4, 2),
	(5, 1)
ON CONFLICT (vet_id, specialty_id) DO NOTHING;

INSERT INTO types (id, name) VALUES
	(1, 'cat'),
	(2, 'dog'),
	(3, 'lizard'),
	(4, 'snake'),
	(5, 'bird'),
	(6, 'hamster')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('types', 'id'), greatest((SELECT max(id) FROM types), 1));

INSERT INTO owners (id, first_name, last_name, address, city, telephone) VALUES
	(1, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023'),
	(2, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749'),
	(3, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763'),
	(4, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198'),
	(5, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765'),
	(6, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654'),
	(7, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387'),
	(8, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683'),
	(9, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435'),
	(10, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('owners', 'id'), greatest((SELECT max(id) FROM owners), 1));

INSERT INTO pets (id, name, birth_date, type_id, owner_id) VALUES
	(1, 'Leo', '2000-09-07', 1, 1),
	(2, 'Basil', '2002-08-06', 6, 2),
	(3, 'Rosy', '2001-04-17', 2, 3),
	(4, 'Jewel', '2000-03-07', 2, 3),
	(5, 'Iggy', '2000-11-30', 3, 4),
	(6, 'George', '2000-01-20', 4, 5),
	(7, 'Samantha', '1995-09-04', 1, 6),
	(8, 'Max', '1995-09-04', 1, 6),
	(9, 'Lucky', '1999-08-06', 5, 7),
	(10, 'Mulligan', '1997-02-24', 2, 8),
	(11, 'Freddy', '2000-03-09', 5, 9),
	(12, 'Lucky', '2000-06-24', 2, 10),
	(13, 'Sly', '2002-06-08', 1, 10)
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('pets', 'id'), greatest((SELECT max(id) FROM pets), 1));

INSERT INTO visits (id, pet_id, visit_date, description) VALUES
	(1, 7, '2010-03-04', 'rabies shot'),
	(2, 8, '2011-03-04', 'rabies shot'),
	(3, 8, '2009-06-04', 'neutered'),
	(4, 7, '2008-09-04', 'spayed')
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('visits', 'id'), greatest((SELECT max(id) FROM visits), 1));`
