// Code generated by Spice. DO NOT EDIT.
// Source: postgres/vet_repository.go:16
//go:build !spice_generate

package postgres

import (
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
)

// spiceImplementsd39886098db3 verifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|13:VetRepository.
var spiceImplementsd39886098db3 vet.Repository = *new(*VetRepository)
