//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: presentation/renderer.go:20

package spicegen

import (
	fmt "fmt"

	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	view "github.com/StevenBuglione/spice/view"
)

// Construct3dddedb0bd5d performs the direct construction selected for spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer.
func Construct3dddedb0bd5d(dependency0 *i18n.Catalog) (*view.Renderer, spicelifecycle.Cleanup, error) {
	value, err := presentation.NewRenderer(dependency0)
	if err != nil {
		var zero *view.Renderer
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer (*github.com/StevenBuglione/spice/view.Renderer): %w", err)
	}
	return value, nil, nil
}
