//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: presentation/server.go:31

package spicegen

import (
	fmt "fmt"
	http "net/http"

	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructServer_2f66240e performs the direct construction selected for bean "newServer".
// Spice source identity: spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer.
func ConstructServer_2f66240e(dependency0 presentation.ServerSettings, dependency1 *http.ServeMux) (*presentation.Server, spicelifecycle.Cleanup, error) {
	value, err := presentation.NewServer(dependency0, dependency1)
	if err != nil {
		var zero *presentation.Server
		return zero, nil, fmt.Errorf("construct bean newServer (*github.com/StevenBuglione/spice/examples/petclinic/presentation.Server, source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer): %w", err)
	}
	return value, nil, nil
}
