package load

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

func TestLoadHonorsEnvironment(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/environment\n\ngo 1.23.0\n",
		"selected/default.go": `//go:build !spice_env

package selected

var Default int
`,
		"selected/environment.go": `//go:build spice_env

package selected

var FromEnvironment int
`,
	})

	program, err := Load(context.Background(), Options{
		Dir: dir,
		Env: replaceEnvironmentValue(os.Environ(), "GOFLAGS", "-tags=spice_env"),
	}, "./...")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	if symbolByID(program.Symbols(), "example.com/environment/selected.FromEnvironment") == nil {
		t.Fatalf("environment-selected declaration missing: %v", symbolIDs(program.Symbols()))
	}
	if symbolByID(program.Symbols(), "example.com/environment/selected.Default") != nil {
		t.Fatalf("default declaration present despite GOFLAGS environment: %v", symbolIDs(program.Symbols()))
	}
}

func TestLoadReturnsStableSymbolOrder(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/order\n\ngo 1.23.0\n",
		"order/order.go": `package order

var Zulu int
const Alpha = 1
type Middle struct{}
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./order")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	got := symbolIDs(program.Symbols())
	want := []string{
		"example.com/order/order",
		"example.com/order/order.Alpha",
		"example.com/order/order.Middle",
		"example.com/order/order.Zulu",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want exact stable order %v", got, want)
	}
}

func TestLoadReturnsStableDiagnosticOrder(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/diagnostics\n\ngo 1.23.0\n",
		"zbroken/z.go": `package zbroken

var Value string = 1
`,
		"abroken/a.go": `package abroken

var Value string = 1
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./zbroken", "./abroken")
	if err == nil {
		t.Fatal("Load() error = nil, want type errors")
	}
	diagnostics := program.Diagnostics()
	got := make([]string, len(diagnostics))
	for i, diagnostic := range diagnostics {
		got[i] = diagnostic.PackagePath + "|" + diagnostic.Kind
	}
	want := []string{
		"example.com/diagnostics/abroken|list",
		"example.com/diagnostics/abroken|type",
		"example.com/diagnostics/zbroken|list",
		"example.com/diagnostics/zbroken|type",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("diagnostics = %v, want exact stable order %v", got, want)
	}
}

func TestLoadCgoUsesSourceDirectoryAndOmitsSyntheticSymbols(t *testing.T) {
	requireCgo(t)

	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/cgosource\n\ngo 1.23.0\n",
		"catalog/catalog.go": `package catalog

/*
static int answer(void) { return 42; }
*/
import "C"

type Service struct{}
var Value = int(C.answer())
func Build() *Service { return &Service{} }
`,
		"catalog/generated.go": `// Code generated by the Spice cgo fixture. DO NOT EDIT.
package catalog

const Generated = 7
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./catalog")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	packages := program.Packages()
	if len(packages) != 1 {
		t.Fatalf("packages = %#v, want one cgo package", packages)
	}
	pkg := packages[0]
	sourceDir := filepath.Join(dir, "catalog")
	if got, want := pkg.Dir, sourceDir; got != want {
		t.Fatalf("package directory = %q, want source directory %q", got, want)
	}
	if !sort.StringsAreSorted(pkg.CompiledGoFiles) {
		t.Fatalf("compiled Go files are not sorted: %v", pkg.CompiledGoFiles)
	}
	hasCacheBackedInput := false
	for _, file := range pkg.CompiledGoFiles {
		if filepath.Dir(file) != sourceDir {
			hasCacheBackedInput = true
			break
		}
	}
	if !hasCacheBackedInput {
		t.Fatalf("compiled Go files = %v, want cgo cache-backed inputs proving integration path executed", pkg.CompiledGoFiles)
	}

	symbols := program.Symbols()
	assertUniqueSymbolIDs(t, symbols)
	if got, want := symbolIDs(symbols), []string{
		"example.com/cgosource/catalog",
		"example.com/cgosource/catalog.Build",
		"example.com/cgosource/catalog.Generated",
		"example.com/cgosource/catalog.Service",
		"example.com/cgosource/catalog.Value",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want source declarations only %v", got, want)
	}

	catalogSource := filepath.Join(sourceDir, "catalog.go")
	generatedSource := filepath.Join(sourceDir, "generated.go")
	wantPosition := map[string]string{
		"example.com/cgosource/catalog":           catalogSource,
		"example.com/cgosource/catalog.Build":     catalogSource,
		"example.com/cgosource/catalog.Generated": generatedSource,
		"example.com/cgosource/catalog.Service":   catalogSource,
		"example.com/cgosource/catalog.Value":     catalogSource,
	}
	for _, symbol := range symbols {
		filename := filepath.Clean(symbol.Position.Filename)
		if filename != wantPosition[symbol.ID] {
			t.Fatalf("symbol %q position = %q, want source file %q", symbol.ID, filename, wantPosition[symbol.ID])
		}
		if strings.Contains(symbol.Name, "_C") || strings.HasPrefix(symbol.Name, "_cgo") || strings.HasPrefix(symbol.Name, "__cgo") {
			t.Fatalf("cgo synthetic declaration entered symbol catalog: %q", symbol.ID)
		}
	}
}

func requireCgo(t *testing.T) {
	t.Helper()
	output, err := exec.Command("go", "env", "CGO_ENABLED").Output()
	if err != nil {
		t.Fatalf("go env CGO_ENABLED: %v", err)
	}
	if strings.TrimSpace(string(output)) != "1" {
		t.Skip("cgo is disabled for this Go toolchain")
	}
	compilerOutput, err := exec.Command("go", "env", "CC").Output()
	if err != nil {
		t.Fatalf("go env CC: %v", err)
	}
	compilerFields := strings.Fields(string(compilerOutput))
	if len(compilerFields) == 0 {
		t.Skip("cgo C compiler is not configured")
	}
	if _, err := exec.LookPath(compilerFields[0]); err != nil {
		t.Skipf("cgo C compiler %q is unavailable", compilerFields[0])
	}
}

func TestLoadOmitsNonAddressableDeclarationsAndReturnsUniqueSymbolIDs(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/identity\n\ngo 1.23.0\n",
		"catalog/first.go": `package catalog

func init() {}

type _ int
func _() {}
var _ = 1
const _ = 2

type Service struct{}
func (Service) _() {}
func (Service) Start() {}

var First int
const FirstConstant = 3
`,
		"catalog/second.go": `package catalog

func init() {}

type _ string
func _() {}
var _ = 4
const _ = 5

func (Service) _() {}

func Build() *Service { return &Service{} }
const Second = 6
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./...")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	symbols := program.Symbols()
	assertUniqueSymbolIDs(t, symbols)
	if got, want := symbolIDs(symbols), []string{
		"example.com/identity/catalog",
		"example.com/identity/catalog.Build",
		"example.com/identity/catalog.First",
		"example.com/identity/catalog.FirstConstant",
		"example.com/identity/catalog.Second",
		"example.com/identity/catalog.Service",
		"example.com/identity/catalog.Service.Start",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want every non-addressable declaration omitted as %v", got, want)
	}
	for _, symbol := range symbols {
		if symbol.Name == "_" || symbol.Name == "init" {
			t.Fatalf("non-addressable %s declaration %q entered symbol catalog: %v", symbol.Kind, symbol.ID, symbolIDs(symbols))
		}
	}
}

func replaceEnvironmentValue(environment []string, name, value string) []string {
	prefix := name + "="
	result := make([]string, 0, len(environment)+1)
	for _, entry := range environment {
		if strings.HasPrefix(entry, prefix) {
			continue
		}
		result = append(result, entry)
	}
	return append(result, prefix+value)
}
