package load

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"
)

const blockingDriverMode = "SPICE_TEST_PACKAGES_DRIVER_BLOCK"

func TestMain(m *testing.M) {
	if os.Getenv(blockingDriverMode) == "1" {
		started := os.Getenv("SPICE_TEST_DRIVER_STARTED")
		pidFile := os.Getenv("SPICE_TEST_DRIVER_PID")
		if started == "" || pidFile == "" {
			os.Exit(2)
		}
		if err := os.WriteFile(pidFile, []byte(strconv.Itoa(os.Getpid())), 0o644); err != nil {
			os.Exit(2)
		}
		if err := os.WriteFile(started, []byte("started"), 0o644); err != nil {
			os.Exit(2)
		}
		for {
			time.Sleep(time.Hour)
		}
	}
	os.Exit(m.Run())
}

func TestLoadHonorsEnvironment(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/environment\n\ngo 1.23.0\n",
		"selected/default.go": `//go:build !spice_env

package selected

var Default int
`,
		"selected/environment.go": `//go:build spice_env

package selected

var FromEnvironment int
`,
	})

	program, err := Load(context.Background(), Options{
		Dir: dir,
		Env: replaceEnvironmentValue(os.Environ(), "GOFLAGS", "-tags=spice_env"),
	}, "./...")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	if symbolByID(program.Symbols(), "example.com/environment/selected.FromEnvironment") == nil {
		t.Fatalf("environment-selected declaration missing: %v", symbolIDs(program.Symbols()))
	}
	if symbolByID(program.Symbols(), "example.com/environment/selected.Default") != nil {
		t.Fatalf("default declaration present despite GOFLAGS environment: %v", symbolIDs(program.Symbols()))
	}
}

func TestLoadReturnsStableSymbolOrder(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/order\n\ngo 1.23.0\n",
		"order/order.go": `package order

var Zulu int
const Alpha = 1
type Middle struct{}
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./order")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	got := symbolIDs(program.Symbols())
	want := []string{
		"example.com/order/order",
		"example.com/order/order.Alpha",
		"example.com/order/order.Middle",
		"example.com/order/order.Zulu",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want exact stable order %v", got, want)
	}
}

func TestLoadReturnsStableDiagnosticOrder(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/diagnostics\n\ngo 1.23.0\n",
		"zbroken/z.go": `package zbroken

var Value string = 1
`,
		"abroken/a.go": `package abroken

var Value string = 1
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./zbroken", "./abroken")
	if err == nil {
		t.Fatal("Load() error = nil, want type errors")
	}
	diagnostics := program.Diagnostics()
	got := make([]string, len(diagnostics))
	for i, diagnostic := range diagnostics {
		got[i] = diagnostic.PackagePath + "|" + diagnostic.Kind
	}
	want := []string{
		"example.com/diagnostics/abroken|list",
		"example.com/diagnostics/abroken|type",
		"example.com/diagnostics/zbroken|list",
		"example.com/diagnostics/zbroken|type",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("diagnostics = %v, want exact stable order %v", got, want)
	}
}

func TestLoadCgoUsesSourceDirectoryAndOmitsSyntheticSymbols(t *testing.T) {
	requireCgo(t)

	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/cgosource\n\ngo 1.23.0\n",
		"catalog/catalog.go": `package catalog

/*
static int answer(void) { return 42; }
*/
import "C"

type Service struct{}
var Value = int(C.answer())
func Build() *Service { return &Service{} }
`,
		"catalog/generated.go": `// Code generated by the Spice cgo fixture. DO NOT EDIT.
package catalog

const Generated = 7
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./catalog")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	packages := program.Packages()
	if len(packages) != 1 {
		t.Fatalf("packages = %#v, want one cgo package", packages)
	}
	pkg := packages[0]
	sourceDir := filepath.Join(dir, "catalog")
	if got, want := pkg.Dir, sourceDir; got != want {
		t.Fatalf("package directory = %q, want source directory %q", got, want)
	}
	if !sort.StringsAreSorted(pkg.CompiledGoFiles) {
		t.Fatalf("compiled Go files are not sorted: %v", pkg.CompiledGoFiles)
	}
	if len(pkg.Files) != len(pkg.CompiledGoFiles) || len(pkg.Syntax) != len(pkg.CompiledGoFiles) {
		t.Fatalf("file model lengths: files=%d compiled=%d syntax=%d", len(pkg.Files), len(pkg.CompiledGoFiles), len(pkg.Syntax))
	}
	for i, file := range pkg.Files {
		if file.PhysicalPath != pkg.CompiledGoFiles[i] || file.Syntax != pkg.Syntax[i] {
			t.Fatalf("file association %d = %#v, compiled=%q syntax=%p", i, file, pkg.CompiledGoFiles[i], pkg.Syntax[i])
		}
		if file.Syntax != nil {
			physical := filepath.Clean(pkg.Raw.Fset.PositionFor(file.Syntax.Pos(), false).Filename)
			if physical != file.PhysicalPath {
				t.Fatalf("file association %d physical syntax path = %q, want %q", i, physical, file.PhysicalPath)
			}
		}
	}
	hasCacheBackedInput := false
	for _, file := range pkg.CompiledGoFiles {
		if filepath.Dir(file) != sourceDir {
			hasCacheBackedInput = true
			break
		}
	}
	if !hasCacheBackedInput {
		t.Fatalf("compiled Go files = %v, want cgo cache-backed inputs proving integration path executed", pkg.CompiledGoFiles)
	}

	symbols := program.Symbols()
	assertUniqueSymbolIDs(t, symbols)
	if got, want := symbolIDs(symbols), []string{
		"example.com/cgosource/catalog",
		"example.com/cgosource/catalog.Build",
		"example.com/cgosource/catalog.Generated",
		"example.com/cgosource/catalog.Service",
		"example.com/cgosource/catalog.Value",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want source declarations only %v", got, want)
	}

	catalogSource := filepath.Join(sourceDir, "catalog.go")
	generatedSource := filepath.Join(sourceDir, "generated.go")
	wantPosition := map[string]string{
		"example.com/cgosource/catalog":           catalogSource,
		"example.com/cgosource/catalog.Build":     catalogSource,
		"example.com/cgosource/catalog.Generated": generatedSource,
		"example.com/cgosource/catalog.Service":   catalogSource,
		"example.com/cgosource/catalog.Value":     catalogSource,
	}
	for _, symbol := range symbols {
		filename := filepath.Clean(symbol.Position.Filename)
		if filename != wantPosition[symbol.ID] {
			t.Fatalf("symbol %q position = %q, want source file %q", symbol.ID, filename, wantPosition[symbol.ID])
		}
		if strings.Contains(symbol.Name, "_C") || strings.HasPrefix(symbol.Name, "_cgo") || strings.HasPrefix(symbol.Name, "__cgo") {
			t.Fatalf("cgo synthetic declaration entered symbol catalog: %q", symbol.ID)
		}
	}
}

func TestLoadRetainsLineMappedSourceWithPhysicalAndDisplayPositions(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/linemapped\n\ngo 1.23.0\n",
		"app/app.go": `package app

//line generated/schema.proto:40
var Value int
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./app")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}
	value := symbolByID(program.Symbols(), "example.com/linemapped/app.Value")
	if value == nil {
		t.Fatalf("line-mapped declaration missing: %v", symbolIDs(program.Symbols()))
	}
	physical := filepath.Join(dir, "app", "app.go")
	if got := filepath.Clean(value.PhysicalPosition.Filename); got != physical {
		t.Fatalf("physical filename = %q, want %q", got, physical)
	}
	display := filepath.Join(dir, "app", "generated", "schema.proto")
	if got := filepath.Clean(value.Position.Filename); got != display || value.Position.Line != 40 {
		t.Fatalf("display position = %s, want %s:40", value.Position, display)
	}
}

func TestLoadReturnsDiagnosticsByNumericPosition(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/numericdiagnostics\n\ngo 1.23.0\n",
		"broken/broken.go": `package broken
var Early string = 1







var Late string = 2
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./broken")
	if err == nil {
		t.Fatal("Load() error = nil, want type errors")
	}
	var lines []int
	for _, diagnostic := range program.Diagnostics() {
		if diagnostic.Kind == "type" {
			lines = append(lines, diagnostic.Line)
		}
	}
	if got, want := lines, []int{2, 10}; !reflect.DeepEqual(got, want) {
		t.Fatalf("type diagnostic lines = %v, want numeric order %v; diagnostics=%#v", got, want, program.Diagnostics())
	}
}

func TestLoadCancelsActivePackageDriver(t *testing.T) {
	executable, err := os.Executable()
	if err != nil {
		t.Fatalf("os.Executable(): %v", err)
	}
	dir := writeModule(t, map[string]string{
		"go.mod":     "module example.com/cancelactive\n\ngo 1.23.0\n",
		"app/app.go": "package app\n",
	})
	signalDir := t.TempDir()
	started := filepath.Join(signalDir, "started")
	pidFile := filepath.Join(signalDir, "pid")
	environment := os.Environ()
	environment = replaceEnvironmentValue(environment, "GOPACKAGESDRIVER", executable)
	environment = replaceEnvironmentValue(environment, blockingDriverMode, "1")
	environment = replaceEnvironmentValue(environment, "SPICE_TEST_DRIVER_STARTED", started)
	environment = replaceEnvironmentValue(environment, "SPICE_TEST_DRIVER_PID", pidFile)

	ctx, cancel := context.WithCancel(context.Background())
	result := make(chan struct {
		program *Program
		err     error
	}, 1)
	go func() {
		program, loadErr := Load(ctx, Options{Dir: dir, Env: environment}, "./...")
		result <- struct {
			program *Program
			err     error
		}{program: program, err: loadErr}
	}()

	waitForPath(t, started, 5*time.Second)
	cancel()
	select {
	case loaded := <-result:
		if !errors.Is(loaded.err, context.Canceled) {
			t.Fatalf("Load() error = %v, want context.Canceled", loaded.err)
		}
		if loaded.program != nil {
			t.Fatalf("Load() program = %#v, want nil", loaded.program)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("Load() did not return after cancelling an active package driver")
	}

	if runtime.GOOS == "linux" {
		pidBytes, err := os.ReadFile(pidFile)
		if err != nil {
			t.Fatalf("ReadFile(pid): %v", err)
		}
		pid, err := strconv.Atoi(strings.TrimSpace(string(pidBytes)))
		if err != nil {
			t.Fatalf("driver pid = %q: %v", pidBytes, err)
		}
		deadline := time.Now().Add(2 * time.Second)
		for {
			_, statErr := os.Stat(filepath.Join("/proc", strconv.Itoa(pid)))
			if os.IsNotExist(statErr) {
				break
			}
			if time.Now().After(deadline) {
				t.Fatalf("package driver process %d still exists after Load returned", pid)
			}
			time.Sleep(10 * time.Millisecond)
		}
	}
}

func waitForPath(t *testing.T, path string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for {
		if _, err := os.Stat(path); err == nil {
			return
		} else if !os.IsNotExist(err) {
			t.Fatalf("Stat(%q): %v", path, err)
		}
		if time.Now().After(deadline) {
			t.Fatalf("timed out waiting for %q", path)
		}
		time.Sleep(10 * time.Millisecond)
	}
}

func requireCgo(t *testing.T) {
	t.Helper()
	output, err := exec.Command("go", "env", "CGO_ENABLED").Output()
	if err != nil {
		t.Fatalf("go env CGO_ENABLED: %v", err)
	}
	if strings.TrimSpace(string(output)) != "1" {
		t.Skip("cgo is disabled for this Go toolchain")
	}
	compilerOutput, err := exec.Command("go", "env", "CC").Output()
	if err != nil {
		t.Fatalf("go env CC: %v", err)
	}
	compilerFields := strings.Fields(string(compilerOutput))
	if len(compilerFields) == 0 {
		t.Skip("cgo C compiler is not configured")
	}
	if _, err := exec.LookPath(compilerFields[0]); err != nil {
		t.Skipf("cgo C compiler %q is unavailable", compilerFields[0])
	}
}

func TestLoadOmitsNonAddressableDeclarationsAndReturnsUniqueSymbolIDs(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/identity\n\ngo 1.23.0\n",
		"catalog/first.go": `package catalog

func init() {}

type _ int
func _() {}
var _ = 1
const _ = 2

type Service struct{}
func (Service) _() {}
func (Service) Start() {}

var First int
const FirstConstant = 3
`,
		"catalog/second.go": `package catalog

func init() {}

type _ string
func _() {}
var _ = 4
const _ = 5

func (Service) _() {}

func Build() *Service { return &Service{} }
const Second = 6
`,
	})

	program, err := Load(context.Background(), Options{Dir: dir}, "./...")
	if err != nil {
		t.Fatalf("Load() error = %v", err)
	}

	symbols := program.Symbols()
	assertUniqueSymbolIDs(t, symbols)
	if got, want := symbolIDs(symbols), []string{
		"example.com/identity/catalog",
		"example.com/identity/catalog.Build",
		"example.com/identity/catalog.First",
		"example.com/identity/catalog.FirstConstant",
		"example.com/identity/catalog.Second",
		"example.com/identity/catalog.Service",
		"example.com/identity/catalog.Service.Start",
	}; !reflect.DeepEqual(got, want) {
		t.Fatalf("symbol IDs = %v, want every non-addressable declaration omitted as %v", got, want)
	}
	for _, symbol := range symbols {
		if symbol.Name == "_" || symbol.Name == "init" {
			t.Fatalf("non-addressable %s declaration %q entered symbol catalog: %v", symbol.Kind, symbol.ID, symbolIDs(symbols))
		}
	}
}

func replaceEnvironmentValue(environment []string, name, value string) []string {
	prefix := name + "="
	result := make([]string, 0, len(environment)+1)
	for _, entry := range environment {
		if strings.HasPrefix(entry, prefix) {
			continue
		}
		result = append(result, entry)
	}
	return append(result, prefix+value)
}
