//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/database.go:25

package spicegen

import (
	fmt "fmt"

	postgres "github.com/spice-framework/spice/examples/petclinic/postgres"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructOpenDatabase_af2eac0b performs the direct construction selected for bean "openDatabase".
// Spice source identity: spice:symbol:v1|function|60:github.com/spice-framework/spice/examples/petclinic/postgres|0:|12:OpenDatabase.
func ConstructOpenDatabase_af2eac0b(dependency0 postgres.Settings) (*postgres.Database, spicelifecycle.Cleanup, error) {
	value, cleanup, err := postgres.OpenDatabase(dependency0)
	if err != nil {
		var zero *postgres.Database
		return zero, nil, fmt.Errorf("construct bean openDatabase (*github.com/spice-framework/spice/examples/petclinic/postgres.Database, source spice:symbol:v1|function|60:github.com/spice-framework/spice/examples/petclinic/postgres|0:|12:OpenDatabase): %w", err)
	}
	return value, cleanup, nil
}
