//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/database.go:25

package spicegen

import (
	fmt "fmt"

	postgres "github.com/StevenBuglione/spice/examples/petclinic/postgres"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct0bab1f0e04ba performs the direct construction selected for spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|12:OpenDatabase.
func Construct0bab1f0e04ba(dependency0 postgres.Settings) (*postgres.Database, spicelifecycle.Cleanup, error) {
	value, cleanup, err := postgres.OpenDatabase(dependency0)
	if err != nil {
		var zero *postgres.Database
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|12:OpenDatabase (*github.com/StevenBuglione/spice/examples/petclinic/postgres.Database): %w", err)
	}
	return value, cleanup, nil
}
