//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/owner_repository.go:17

package spicegen

import (
	fmt "fmt"

	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	postgres "github.com/StevenBuglione/spice/examples/petclinic/postgres"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct3fa14a0e2160 performs the direct construction selected for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository.
func Construct3fa14a0e2160(dependency0 *postgres.Database) (*postgres.OwnerRepository, spicelifecycle.Cleanup, error) {
	value, err := postgres.NewOwnerRepository(dependency0)
	if err != nil {
		var zero *postgres.OwnerRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.OwnerRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplements55b41c6d3e05 verifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository.
var spiceImplements55b41c6d3e05 owner.Repository = *new(*postgres.OwnerRepository)
