//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/owner_repository.go:17

package spicegen

import (
	fmt "fmt"

	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	postgres "github.com/StevenBuglione/spice/examples/petclinic/postgres"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructOwnerRepository_3fa14a0e performs the direct construction selected for bean "ownerRepository".
// Spice source identity: spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository.
func ConstructOwnerRepository_3fa14a0e(dependency0 *postgres.Database) (*postgres.OwnerRepository, spicelifecycle.Cleanup, error) {
	value, err := postgres.NewOwnerRepository(dependency0)
	if err != nil {
		var zero *postgres.OwnerRepository
		return zero, nil, fmt.Errorf("construct bean ownerRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.OwnerRepository, source spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsOwnerRepositoryAsRepository_55b41c6d identifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository.
var _ owner.Repository = (*postgres.OwnerRepository)(nil)
