//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/pet_type_repository.go:15

package spicegen

import (
	fmt "fmt"

	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	postgres "github.com/StevenBuglione/spice/examples/petclinic/postgres"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Constructcc9e2d73b4b9 performs the direct construction selected for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository.
func Constructcc9e2d73b4b9(dependency0 *postgres.Database) (*postgres.PetTypeRepository, spicelifecycle.Cleanup, error) {
	value, err := postgres.NewPetTypeRepository(dependency0)
	if err != nil {
		var zero *postgres.PetTypeRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.PetTypeRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsce8e4c99400e verifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository.
var spiceImplementsce8e4c99400e owner.PetTypeRepository = *new(*postgres.PetTypeRepository)
