//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/pet_type_repository.go:15

package spicegen

import (
	fmt "fmt"

	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	postgres "github.com/StevenBuglione/spice/examples/petclinic/postgres"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructPetTypeRepository_cc9e2d73 performs the direct construction selected for bean "petTypeRepository".
// Spice source identity: spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository.
func ConstructPetTypeRepository_cc9e2d73(dependency0 *postgres.Database) (*postgres.PetTypeRepository, spicelifecycle.Cleanup, error) {
	value, err := postgres.NewPetTypeRepository(dependency0)
	if err != nil {
		var zero *postgres.PetTypeRepository
		return zero, nil, fmt.Errorf("construct bean petTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.PetTypeRepository, source spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsPetTypeRepositoryAsPetTypeRepository_ce8e4c99 identifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository.
var _ owner.PetTypeRepository = (*postgres.PetTypeRepository)(nil)
