//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/settings.go:10

package spicegen

import (
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	postgres "github.com/spice-framework/spice/examples/petclinic/postgres"
)

// BindSettings_776f212c binds the validated configuration declared by spice:symbol:v1|type|60:github.com/spice-framework/spice/examples/petclinic/postgres|0:|8:Settings.
func BindSettings_776f212c(configurationSnapshot spiceconfig.Snapshot) (postgres.Settings, error) {
	value := postgres.Settings{}
	if _, configured := configurationSnapshot.Lookup("petclinic.datasource.url"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("petclinic.datasource.url")
		if valueErr != nil {
			return postgres.Settings{}, fmt.Errorf("decode configuration property petclinic.datasource.url for github.com/spice-framework/spice/examples/petclinic/postgres.Settings.URL: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.URL = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("petclinic.datasource.allow-insecure"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("petclinic.datasource.allow-insecure")
		if valueErr != nil {
			return postgres.Settings{}, fmt.Errorf("decode configuration property petclinic.datasource.allow-insecure for github.com/spice-framework/spice/examples/petclinic/postgres.Settings.AllowInsecure: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.AllowInsecure = convertedValue
	}
	return value, nil
}
