//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/vet_repository.go:16

package spicegen

import (
	fmt "fmt"

	postgres "github.com/spice-framework/spice/examples/petclinic/postgres"
	vet "github.com/spice-framework/spice/examples/petclinic/vet"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructVetRepository_e94dad1c performs the direct construction selected for bean "vetRepository".
// Spice source identity: spice:symbol:v1|type|60:github.com/spice-framework/spice/examples/petclinic/postgres|0:|13:VetRepository.
func ConstructVetRepository_e94dad1c(dependency0 *postgres.Database) (*postgres.VetRepository, spicelifecycle.Cleanup, error) {
	value, err := postgres.NewVetRepository(dependency0)
	if err != nil {
		var zero *postgres.VetRepository
		return zero, nil, fmt.Errorf("construct bean vetRepository (*github.com/spice-framework/spice/examples/petclinic/postgres.VetRepository, source spice:symbol:v1|type|60:github.com/spice-framework/spice/examples/petclinic/postgres|0:|13:VetRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsVetRepositoryAsRepository_16053349 identifies the explicit @Implements binding for spice:symbol:v1|type|60:github.com/spice-framework/spice/examples/petclinic/postgres|0:|13:VetRepository.
var _ vet.Repository = (*postgres.VetRepository)(nil)
