//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: postgres/vet_repository.go:16

package spicegen

import (
	fmt "fmt"

	postgres "github.com/StevenBuglione/spice/examples/petclinic/postgres"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructVetRepository_0bc65553 performs the direct construction selected for bean "vetRepository".
// Spice source identity: spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|13:VetRepository.
func ConstructVetRepository_0bc65553(dependency0 *postgres.Database) (*postgres.VetRepository, spicelifecycle.Cleanup, error) {
	value, err := postgres.NewVetRepository(dependency0)
	if err != nil {
		var zero *postgres.VetRepository
		return zero, nil, fmt.Errorf("construct bean vetRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.VetRepository, source spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|13:VetRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsVetRepositoryAsRepository_d3988609 verifies the explicit @Implements binding for spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|13:VetRepository.
var spiceImplementsVetRepositoryAsRepository_d3988609 vet.Repository = *new(*postgres.VetRepository)
