//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/owner_repository.go:17

package mysql

import (
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
)

// spiceImplements3593c16a667f verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository.
var spiceImplements3593c16a667f owner.Repository = *new(*OwnerRepository)
