//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/pet_type_repository.go:15

package mysql

import (
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
)

// spiceImplementsda9a4220854d verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository.
var spiceImplementsda9a4220854d owner.PetTypeRepository = *new(*PetTypeRepository)
