//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/vet_repository.go:16

package mysql

import (
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
)

// spiceImplements91b1c4460a3f verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|13:VetRepository.
var spiceImplements91b1c4460a3f vet.Repository = *new(*VetRepository)
