//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	slog "log/slog"
	os "os"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spicemanagement "github.com/StevenBuglione/spice/management"
	spiceobservability "github.com/StevenBuglione/spice/observability"
	spiceweb "github.com/StevenBuglione/spice/web"
)

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application mysql: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	httpObservers := append([]spiceweb.HTTPObserver(nil), options.HTTPObservers...)
	_ = httpObservers
	managementMetrics := spicemanagement.NewHTTPMetrics()
	httpObservers = append([]spiceweb.HTTPObserver{managementMetrics}, httpObservers...)
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(os.Stderr, nil))
	}
	lifecycleLogs, err := spiceobservability.NewSlogLifecycleObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure lifecycle logging: %w", err))
	}
	observers = append([]spicelifecycle.Observer{lifecycleLogs}, observers...)
	httpLogs, err := spiceobservability.NewSlogHTTPObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure HTTP logging: %w", err))
	}
	httpObservers = append(httpObservers[:1], append([]spiceweb.HTTPObserver{httpLogs}, httpObservers[1:]...)...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application mysql: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application mysql: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application mysql: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application mysql: duration must be positive"))
	}
	dependencies, err := constructApplicationDependencies(ctx, application, options, configurationSnapshot)
	if err != nil {
		return nil, err
	}
	_ = dependencies
	application.components = Components{
		Catalog:           dependencies.catalog,
		Renderer:          dependencies.renderer,
		Mux:               dependencies.mux,
		Settings:          dependencies.settings,
		OpenDatabase:      dependencies.openDatabase,
		VetRepository:     dependencies.vetRepository,
		VetController:     dependencies.vetController,
		OwnerRepository:   dependencies.ownerRepository,
		PetTypeRepository: dependencies.petTypeRepository,
		OwnerController:   dependencies.ownerController,
		PetController:     dependencies.petController,
		VisitController:   dependencies.visitController,
		WelcomeController: dependencies.welcomeController,
		ServerSettings:    dependencies.serverSettings,
		Server:            dependencies.server,
	}
	if _, err := configureGeneratedLifecycle(ctx, application, options, dependencies); err != nil {
		return nil, err
	}
	if _, err := configureGeneratedHTTP(
		ctx,
		application,
		options,
		configurationSchema,
		configurationSnapshot,
		dependencies,
		httpObservers,
		managementMetrics,
	); err != nil {
		return nil, err
	}
	return application, nil
}
