//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/StevenBuglione/spice/config"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	spiceintercept "github.com/StevenBuglione/spice/intercept"
	spiceweb "github.com/StevenBuglione/spice/web"
)

func registerGeneratedRouteVetControllerListJSON_5badfbec(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	routeMux *http.ServeMux,
) (*Application, error) {
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|54:github.com/StevenBuglione/spice/examples/petclinic/vet|10:Controller|8:ListJSON", Module: "", Method: "GET", Pattern: "/vets"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /vets observation: %w", routeObservationErr0))
	}
	routeTerminal := func(invocationContext context.Context, invocationRequest vet.AllRequest) (vet.Vets, error) {
		return dependencies.vetController.ListJSON(invocationContext, invocationRequest)
	}
	routeInvocation, routeInterceptorErr := spiceintercept.Chain(
		routeTerminal,
		options.Interceptors.ControllerListJSON...,
	)
	if routeInterceptorErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct generated typed interceptors for route GET /vets: %w", routeInterceptorErr))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /vets", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return spiceweb.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceweb.AcceptsJSON(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces application/json",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := vet.AllRequest{}
		responseValue, routeErr := routeInvocation(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = spiceweb.WriteJSON(writer, http.StatusOK, responseValue)
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /vets: %w", routeErr))
	}
	return application, nil
}
