//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spiceMysql "github.com/StevenBuglione/spice/examples/petclinic/internal/spicegen/mysql/sources/mysql"
	spiceOwner "github.com/StevenBuglione/spice/examples/petclinic/internal/spicegen/mysql/sources/owner"
	spicePresentation "github.com/StevenBuglione/spice/examples/petclinic/internal/spicegen/mysql/sources/presentation"
	spiceSystem "github.com/StevenBuglione/spice/examples/petclinic/internal/spicegen/mysql/sources/system"
	spiceVet "github.com/StevenBuglione/spice/examples/petclinic/internal/spicegen/mysql/sources/vet"
	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	system "github.com/StevenBuglione/spice/examples/petclinic/system"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spiceview "github.com/StevenBuglione/spice/view"
)

type applicationDependencies struct {
	catalog           *i18n.Catalog
	renderer          *spiceview.Renderer
	mux               *http.ServeMux
	settings          mysql.Settings
	openDatabase      *mysql.Database
	vetRepository     *mysql.VetRepository
	vetController     *vet.Controller
	ownerRepository   *mysql.OwnerRepository
	petTypeRepository *mysql.PetTypeRepository
	ownerController   *owner.Controller
	petController     *owner.PetController
	visitController   *owner.VisitController
	welcomeController *system.WelcomeController
	serverSettings    presentation.ServerSettings
	server            *presentation.Server
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	catalog, catalogCleanup, err := func() (*i18n.Catalog, spicelifecycle.Cleanup, error) {
		if options.Overrides.Catalog.Enabled() {
			return options.Overrides.Catalog.Acquire(ctx)
		}
		return spicePresentation.ConstructCatalog_6e1785b3()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newCatalog (*github.com/StevenBuglione/spice/i18n.Catalog, source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|10:NewCatalog): %w", err))
	}
	if catalogCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|10:NewCatalog", catalogCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newCatalog (source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|10:NewCatalog): %w", err))
		}
	}
	_ = catalog
	renderer, rendererCleanup, err := func() (*spiceview.Renderer, spicelifecycle.Cleanup, error) {
		if options.Overrides.Renderer.Enabled() {
			return options.Overrides.Renderer.Acquire(ctx)
		}
		return spicePresentation.ConstructRenderer_3dddedb0(catalog)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newRenderer (*github.com/StevenBuglione/spice/view.Renderer, source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer): %w", err))
	}
	if rendererCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer", rendererCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newRenderer (source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer): %w", err))
		}
	}
	_ = renderer
	mux, muxCleanup, err := func() (*http.ServeMux, spicelifecycle.Cleanup, error) {
		if options.Overrides.Mux.Enabled() {
			return options.Overrides.Mux.Acquire(ctx)
		}
		return spicePresentation.ConstructMux_1ec2a68a()
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newMux (*net/http.ServeMux, source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|6:NewMux): %w", err))
	}
	if muxCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|6:NewMux", muxCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newMux (source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|6:NewMux): %w", err))
		}
	}
	_ = mux
	settings, err := spiceMysql.BindSettings_e87de823(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/petclinic/mysql.Settings for bean Settings (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|8:Settings): %w", err))
	}
	_ = settings
	openDatabase, openDatabaseCleanup, err := func() (*mysql.Database, spicelifecycle.Cleanup, error) {
		if options.Overrides.OpenDatabase.Enabled() {
			return options.Overrides.OpenDatabase.Acquire(ctx)
		}
		return spiceMysql.ConstructOpenDatabase_fc953d95(settings)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean openDatabase (*github.com/StevenBuglione/spice/examples/petclinic/mysql.Database, source spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|12:OpenDatabase): %w", err))
	}
	if openDatabaseCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|12:OpenDatabase", openDatabaseCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean openDatabase (source spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|12:OpenDatabase): %w", err))
		}
	}
	_ = openDatabase
	vetRepository, vetRepositoryCleanup, err := func() (*mysql.VetRepository, spicelifecycle.Cleanup, error) {
		if options.Overrides.VetRepository.Enabled() {
			return options.Overrides.VetRepository.Acquire(ctx)
		}
		return spiceMysql.ConstructVetRepository_e6a8bff4(openDatabase)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean vetRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.VetRepository, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|13:VetRepository): %w", err))
	}
	if vetRepositoryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|13:VetRepository", vetRepositoryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean vetRepository (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|13:VetRepository): %w", err))
		}
	}
	_ = vetRepository
	vetController, vetControllerCleanup, err := func() (*vet.Controller, spicelifecycle.Cleanup, error) {
		if options.Overrides.VetController.Enabled() {
			return options.Overrides.VetController.Acquire(ctx)
		}
		return spiceVet.ConstructController_8580f4b8(vetRepository, catalog)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean controller (*github.com/StevenBuglione/spice/examples/petclinic/vet.Controller, source spice:symbol:v1|type|54:github.com/StevenBuglione/spice/examples/petclinic/vet|0:|10:Controller): %w", err))
	}
	if vetControllerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|54:github.com/StevenBuglione/spice/examples/petclinic/vet|0:|10:Controller", vetControllerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean controller (source spice:symbol:v1|type|54:github.com/StevenBuglione/spice/examples/petclinic/vet|0:|10:Controller): %w", err))
		}
	}
	_ = vetController
	ownerRepository, ownerRepositoryCleanup, err := func() (*mysql.OwnerRepository, spicelifecycle.Cleanup, error) {
		if options.Overrides.OwnerRepository.Enabled() {
			return options.Overrides.OwnerRepository.Acquire(ctx)
		}
		return spiceMysql.ConstructOwnerRepository_055f5543(openDatabase)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean ownerRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.OwnerRepository, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository): %w", err))
	}
	if ownerRepositoryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository", ownerRepositoryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean ownerRepository (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository): %w", err))
		}
	}
	_ = ownerRepository
	petTypeRepository, petTypeRepositoryCleanup, err := func() (*mysql.PetTypeRepository, spicelifecycle.Cleanup, error) {
		if options.Overrides.PetTypeRepository.Enabled() {
			return options.Overrides.PetTypeRepository.Acquire(ctx)
		}
		return spiceMysql.ConstructPetTypeRepository_1ad039a7(openDatabase)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean petTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.PetTypeRepository, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository): %w", err))
	}
	if petTypeRepositoryCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository", petTypeRepositoryCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean petTypeRepository (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository): %w", err))
		}
	}
	_ = petTypeRepository
	ownerController, ownerControllerCleanup, err := func() (*owner.Controller, spicelifecycle.Cleanup, error) {
		if options.Overrides.OwnerController.Enabled() {
			return options.Overrides.OwnerController.Acquire(ctx)
		}
		return spiceOwner.ConstructController_6d9e55b6(ownerRepository, catalog)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean controller (*github.com/StevenBuglione/spice/examples/petclinic/owner.Controller, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|10:Controller): %w", err))
	}
	if ownerControllerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|10:Controller", ownerControllerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean controller (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|10:Controller): %w", err))
		}
	}
	_ = ownerController
	petController, petControllerCleanup, err := func() (*owner.PetController, spicelifecycle.Cleanup, error) {
		if options.Overrides.PetController.Enabled() {
			return options.Overrides.PetController.Acquire(ctx)
		}
		return spiceOwner.ConstructPetController_fb101c0a(ownerRepository, petTypeRepository, catalog)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean petController (*github.com/StevenBuglione/spice/examples/petclinic/owner.PetController, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|13:PetController): %w", err))
	}
	if petControllerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|13:PetController", petControllerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean petController (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|13:PetController): %w", err))
		}
	}
	_ = petController
	visitController, visitControllerCleanup, err := func() (*owner.VisitController, spicelifecycle.Cleanup, error) {
		if options.Overrides.VisitController.Enabled() {
			return options.Overrides.VisitController.Acquire(ctx)
		}
		return spiceOwner.ConstructVisitController_6bd173f5(ownerRepository, catalog)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean visitController (*github.com/StevenBuglione/spice/examples/petclinic/owner.VisitController, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|15:VisitController): %w", err))
	}
	if visitControllerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|15:VisitController", visitControllerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean visitController (source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|15:VisitController): %w", err))
		}
	}
	_ = visitController
	welcomeController, welcomeControllerCleanup, err := func() (*system.WelcomeController, spicelifecycle.Cleanup, error) {
		if options.Overrides.WelcomeController.Enabled() {
			return options.Overrides.WelcomeController.Acquire(ctx)
		}
		return spiceSystem.ConstructWelcomeController_0b0c501d(catalog)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean welcomeController (*github.com/StevenBuglione/spice/examples/petclinic/system.WelcomeController, source spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/system|0:|17:WelcomeController): %w", err))
	}
	if welcomeControllerCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/system|0:|17:WelcomeController", welcomeControllerCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean welcomeController (source spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/system|0:|17:WelcomeController): %w", err))
		}
	}
	_ = welcomeController
	serverSettings, err := spicePresentation.BindServerSettings_450eac75(configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("bind configuration github.com/StevenBuglione/spice/examples/petclinic/presentation.ServerSettings for bean ServerSettings (source spice:symbol:v1|type|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|14:ServerSettings): %w", err))
	}
	_ = serverSettings
	server, serverCleanup, err := func() (*presentation.Server, spicelifecycle.Cleanup, error) {
		if options.Overrides.Server.Enabled() {
			return options.Overrides.Server.Acquire(ctx)
		}
		return spicePresentation.ConstructServer_2f66240e(serverSettings, mux)
	}()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean newServer (*github.com/StevenBuglione/spice/examples/petclinic/presentation.Server, source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer): %w", err))
	}
	if serverCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer", serverCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean newServer (source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer): %w", err))
		}
	}
	_ = server
	return &applicationDependencies{
		catalog:           catalog,
		renderer:          renderer,
		mux:               mux,
		settings:          settings,
		openDatabase:      openDatabase,
		vetRepository:     vetRepository,
		vetController:     vetController,
		ownerRepository:   ownerRepository,
		petTypeRepository: petTypeRepository,
		ownerController:   ownerController,
		petController:     petController,
		visitController:   visitController,
		welcomeController: welcomeController,
		serverSettings:    serverSettings,
		server:            server,
	}, nil
}
