//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spicemanagement "github.com/StevenBuglione/spice/management"
	spiceweb "github.com/StevenBuglione/spice/web"
)

func configureGeneratedHTTP(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSchema spiceconfig.Schema,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	managementMetrics *spicemanagement.HTTPMetrics,
) (*Application, error) {
	_ = configurationSchema
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeMux := dependencies.mux
	application.mux = routeMux
	application.handler = routeMux
	if _, err := registerGeneratedRouteVetControllerListJSON_5badfbec(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteVetControllerListHTML_d306b13c(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerFind_49afddd0(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerFindForm_d73d965f(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerNewForm_ebdcb72a(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerShow_b5b989ae(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerEditForm_7455f8a2(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerCreate_92cf9af6(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerUpdate_85d595d3(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerNewForm_9df899ef(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerEditForm_d35ff46f(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerCreate_55f9d3e7(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerUpdate_4692814b(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerVisitControllerNewForm_415f0e67(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerVisitControllerCreate_6208272f(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteSystemWelcomeControllerShow_94e120b7(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	managementChecks, err := spicemanagement.LifecycleChecks(TargetID, "github.com/StevenBuglione/spice/examples/petclinic/cmd/mysql", application.State)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management lifecycle checks: %w", err))
	}
	managementManager, err := spicemanagement.New(managementChecks...)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management checks: %w", err))
	}
	managementConfiguration, err := spicemanagement.NewConfigurationReport(configurationSchema, configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management configuration report: %w", err))
	}
	managementModules, err := spicemanagement.NewModuleReport(
		[]spicemanagement.ModuleDefinition{},
		[]spicemanagement.ModuleEdge{},
		[]string{},
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management module report: %w", err))
	}
	managementHandler, err := spicemanagement.NewHandler(spicemanagement.HandlerOptions{
		Manager: managementManager,
		Info: map[string]string{
			"application": TargetID,
			"module":      "github.com/StevenBuglione/spice/examples/petclinic/cmd/mysql",
			"framework":   "Spice",
		},
		Metrics:       managementMetrics,
		Configuration: &managementConfiguration,
		Modules:       &managementModules,
		Expose: []spicemanagement.Endpoint{
			spicemanagement.EndpointConfigProps,
			spicemanagement.EndpointHealth,
			spicemanagement.EndpointInfo,
			spicemanagement.EndpointLiveness,
			spicemanagement.EndpointMetrics,
			spicemanagement.EndpointModules,
			spicemanagement.EndpointReadiness,
		},
		Access: spicemanagement.Access("loopback"),
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management handler: %w", err))
	}
	if err := spiceweb.Register(routeMux, managementHandler.Pattern(), managementHandler); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register management routes: %w", err))
	}
	return application, nil
}
