//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"

	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

func configureGeneratedLifecycle(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	dependencies *applicationDependencies,
) (*Application, error) {
	_ = ctx
	_ = options
	_ = dependencies
	application.hooks = []spicelifecycle.Hook{
		{
			ID:     "spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|12:OpenDatabase",
			Module: "",
			Start:  dependencies.provider4.Migrate,
		},
		{
			ID:     "spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer",
			Module: "",
			Start:  dependencies.provider14.Start,
			Stop:   dependencies.provider14.Stop,
		},
	}
	return application, nil
}
