//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	slog "log/slog"
	http "net/http"
	strings "strings"
	time "time"

	spicebean "github.com/spice-framework/spice/bean"
	spiceconfig "github.com/spice-framework/spice/config"
	spiceentrypoint "github.com/spice-framework/spice/examples/petclinic/internal/spicegen/mysql/sources/cmd/mysql"
	mysql "github.com/spice-framework/spice/examples/petclinic/mysql"
	owner "github.com/spice-framework/spice/examples/petclinic/owner"
	presentation "github.com/spice-framework/spice/examples/petclinic/presentation"
	system "github.com/spice-framework/spice/examples/petclinic/system"
	vet "github.com/spice-framework/spice/examples/petclinic/vet"
	i18n "github.com/spice-framework/spice/i18n"
	spiceintercept "github.com/spice-framework/spice/intercept"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
	spiceview "github.com/spice-framework/spice/view"
	spiceweb "github.com/spice-framework/spice/web"
)

const TargetID = spiceentrypoint.ApplicationTargetMysql_89cf8ad0

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// Catalog is bean "newCatalog".
	Catalog *i18n.Catalog
	// Renderer is bean "newRenderer".
	Renderer *spiceview.Renderer
	// Mux is bean "newMux".
	Mux *http.ServeMux
	// Settings is bean "Settings".
	Settings mysql.Settings
	// OpenDatabase is bean "openDatabase".
	OpenDatabase *mysql.Database
	// VetRepository is bean "vetRepository".
	VetRepository *mysql.VetRepository
	// VetController is bean "controller".
	VetController *vet.Controller
	// OwnerRepository is bean "ownerRepository".
	OwnerRepository *mysql.OwnerRepository
	// PetTypeRepository is bean "petTypeRepository".
	PetTypeRepository *mysql.PetTypeRepository
	// OwnerController is bean "controller".
	OwnerController *owner.Controller
	// PetController is bean "petController".
	PetController *owner.PetController
	// VisitController is bean "visitController".
	VisitController *owner.VisitController
	// WelcomeController is bean "welcomeController".
	WelcomeController *system.WelcomeController
	// ServerSettings is bean "ServerSettings".
	ServerSettings presentation.ServerSettings
	// Server is bean "newServer".
	Server *presentation.Server
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// Catalog replaces bean "newCatalog".
	Catalog spicebean.Override[*i18n.Catalog]
	// Renderer replaces bean "newRenderer".
	Renderer spicebean.Override[*spiceview.Renderer]
	// Mux replaces bean "newMux".
	Mux spicebean.Override[*http.ServeMux]
	// OpenDatabase replaces bean "openDatabase".
	OpenDatabase spicebean.Override[*mysql.Database]
	// VetRepository replaces bean "vetRepository".
	VetRepository spicebean.Override[*mysql.VetRepository]
	// VetController replaces bean "controller".
	VetController spicebean.Override[*vet.Controller]
	// OwnerRepository replaces bean "ownerRepository".
	OwnerRepository spicebean.Override[*mysql.OwnerRepository]
	// PetTypeRepository replaces bean "petTypeRepository".
	PetTypeRepository spicebean.Override[*mysql.PetTypeRepository]
	// OwnerController replaces bean "controller".
	OwnerController spicebean.Override[*owner.Controller]
	// PetController replaces bean "petController".
	PetController spicebean.Override[*owner.PetController]
	// VisitController replaces bean "visitController".
	VisitController spicebean.Override[*owner.VisitController]
	// WelcomeController replaces bean "welcomeController".
	WelcomeController spicebean.Override[*system.WelcomeController]
	// Server replaces bean "newServer".
	Server spicebean.Override[*presentation.Server]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.Catalog.Enabled() {
			result.Catalog = layer.Overrides.Catalog
		}
		if layer.Overrides.Renderer.Enabled() {
			result.Renderer = layer.Overrides.Renderer
		}
		if layer.Overrides.Mux.Enabled() {
			result.Mux = layer.Overrides.Mux
		}
		if layer.Overrides.OpenDatabase.Enabled() {
			result.OpenDatabase = layer.Overrides.OpenDatabase
		}
		if layer.Overrides.VetRepository.Enabled() {
			result.VetRepository = layer.Overrides.VetRepository
		}
		if layer.Overrides.VetController.Enabled() {
			result.VetController = layer.Overrides.VetController
		}
		if layer.Overrides.OwnerRepository.Enabled() {
			result.OwnerRepository = layer.Overrides.OwnerRepository
		}
		if layer.Overrides.PetTypeRepository.Enabled() {
			result.PetTypeRepository = layer.Overrides.PetTypeRepository
		}
		if layer.Overrides.OwnerController.Enabled() {
			result.OwnerController = layer.Overrides.OwnerController
		}
		if layer.Overrides.PetController.Enabled() {
			result.PetController = layer.Overrides.PetController
		}
		if layer.Overrides.VisitController.Enabled() {
			result.VisitController = layer.Overrides.VisitController
		}
		if layer.Overrides.WelcomeController.Enabled() {
			result.WelcomeController = layer.Overrides.WelcomeController
		}
		if layer.Overrides.Server.Enabled() {
			result.Server = layer.Overrides.Server
		}
	}
	return result, nil
}

// RouteInterceptors configures typed generated route method decorators.
// The first interceptor in each field is the outermost invocation.
type RouteInterceptors struct {
	ControllerListJSON     []spiceintercept.Interceptor[vet.AllRequest, vet.Vets]
	ControllerListHTML     []spiceintercept.Interceptor[vet.ListRequest, spiceview.Result]
	ControllerFind         []spiceintercept.Interceptor[owner.FindOwnersRequest, spiceview.Result]
	ControllerFindForm     []spiceintercept.Interceptor[owner.FindOwnerFormRequest, spiceview.Result]
	ControllerNewForm      []spiceintercept.Interceptor[owner.NewOwnerRequest, spiceview.Result]
	ControllerShow         []spiceintercept.Interceptor[owner.OwnerIDRequest, spiceview.Result]
	ControllerEditForm     []spiceintercept.Interceptor[owner.OwnerIDRequest, spiceview.Result]
	PetControllerNewForm   []spiceintercept.Interceptor[owner.NewPetRequest, spiceview.Result]
	PetControllerEditForm  []spiceintercept.Interceptor[owner.OwnerPetRequest, spiceview.Result]
	VisitControllerNewForm []spiceintercept.Interceptor[owner.NewVisitRequest, spiceview.Result]
	WelcomeControllerShow  []spiceintercept.Interceptor[system.WelcomeRequest, spiceview.Result]
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
	mux             *http.ServeMux
	handler         http.Handler
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	ErrorMapper               spiceweb.ErrorMapper
	MaxRequestBodyBytes       int64
	HTTPObservers             []spiceweb.HTTPObserver
	Middleware                []spiceweb.Middleware
	Interceptors              RouteInterceptors
	Logger                    *slog.Logger
	Observers                 []spicelifecycle.Observer
}
