//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	slog "log/slog"
	http "net/http"
	time "time"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spiceentrypoint "github.com/StevenBuglione/spice/examples/petclinic/internal/spicegen/mysql/sources/cmd/mysql"
	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	system "github.com/StevenBuglione/spice/examples/petclinic/system"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spiceview "github.com/StevenBuglione/spice/view"
	spiceweb "github.com/StevenBuglione/spice/web"
)

const TargetID = spiceentrypoint.ApplicationTarget47bdf520c582

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// Catalog is bean "newCatalog".
	Catalog *i18n.Catalog
	// Renderer is bean "newRenderer".
	Renderer *spiceview.Renderer
	// Mux is bean "newMux".
	Mux *http.ServeMux
	// Settings is bean "Settings".
	Settings mysql.Settings
	// OpenDatabase is bean "openDatabase".
	OpenDatabase *mysql.Database
	// VetRepository is bean "vetRepository".
	VetRepository *mysql.VetRepository
	// VetController is bean "controller".
	VetController *vet.Controller
	// OwnerRepository is bean "ownerRepository".
	OwnerRepository *mysql.OwnerRepository
	// PetTypeRepository is bean "petTypeRepository".
	PetTypeRepository *mysql.PetTypeRepository
	// OwnerController is bean "controller".
	OwnerController *owner.Controller
	// PetController is bean "petController".
	PetController *owner.PetController
	// VisitController is bean "visitController".
	VisitController *owner.VisitController
	// WelcomeController is bean "welcomeController".
	WelcomeController *system.WelcomeController
	// ServerSettings is bean "ServerSettings".
	ServerSettings presentation.ServerSettings
	// Server is bean "newServer".
	Server *presentation.Server
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
	mux             *http.ServeMux
	handler         http.Handler
}

type ApplicationOptions struct {
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	ErrorMapper               spiceweb.ErrorMapper
	MaxRequestBodyBytes       int64
	HTTPObservers             []spiceweb.HTTPObserver
	Middleware                []spiceweb.Middleware
	Logger                    *slog.Logger
	Observers                 []spicelifecycle.Observer
}
