//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/spice-framework/spice/config"
	system "github.com/spice-framework/spice/examples/petclinic/system"
	spiceintercept "github.com/spice-framework/spice/intercept"
	spiceview "github.com/spice-framework/spice/view"
	spiceweb "github.com/spice-framework/spice/web"
)

func registerGeneratedRouteSystemWelcomeControllerShow_51a573a3(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	routeMux *http.ServeMux,
) (*Application, error) {
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|58:github.com/spice-framework/spice/examples/petclinic/system|17:WelcomeController|4:Show", Module: "", Method: "GET", Pattern: "/"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET / observation: %w", routeObservationErr0))
	}
	routeTerminal := func(invocationContext context.Context, invocationRequest system.WelcomeRequest) (spiceview.Result, error) {
		return dependencies.welcomeController.Show(invocationContext, invocationRequest)
	}
	routeInvocation, routeInterceptorErr := spiceintercept.Chain(
		routeTerminal,
		options.Interceptors.WelcomeControllerShow...,
	)
	if routeInterceptorErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct generated typed interceptors for route GET /: %w", routeInterceptorErr))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return dependencies.renderer.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := system.WelcomeRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			requestValue.Language = string(raw0)
		}
		responseValue, routeErr := routeInvocation(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = dependencies.renderer.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /: %w", routeErr))
	}
	return application, nil
}
