//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	component "example.com/spice-annotation-app/component"
	spicesource0 "example.com/spice-annotation-app/internal/spicegen/spice_annotation_app/sources/component"
	spiceconfig "github.com/StevenBuglione/spice/config"
)

type applicationDependencies struct {
	provider0 component.Message
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	provider0, cleanup0, err := spicesource0.Construct031f9b839d45()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage (example.com/spice-annotation-app/component.Message): %w", err))
	}
	if cleanup0 != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage", cleanup0); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for provider spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage: %w", err))
		}
	}
	_ = provider0
	return &applicationDependencies{
		provider0: provider0,
	}, nil
}
