//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	time "time"

	component "example.com/spice-annotation-app/component"
	spiceentrypoint "example.com/spice-annotation-app/internal/spicegen/spice_annotation_app/sources/_root"
	spicebean "github.com/StevenBuglione/spice/bean"
	spiceconfig "github.com/StevenBuglione/spice/config"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

const TargetID = spiceentrypoint.ApplicationTargetSpiceAnnotationApp_064f9950

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// ProvideMessage is bean "provideMessage".
	ProvideMessage component.Message
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// ProvideMessage replaces bean "provideMessage".
	ProvideMessage spicebean.Override[component.Message]
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
