//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	fmt "fmt"
	strings "strings"
	time "time"

	component "example.com/spice-annotation-app/component"
	spiceentrypoint "example.com/spice-annotation-app/internal/spicegen/spice_annotation_app/sources/_root"
	spicebean "github.com/StevenBuglione/spice/bean"
	spiceconfig "github.com/StevenBuglione/spice/config"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

const TargetID = spiceentrypoint.ApplicationTargetSpiceAnnotationApp_064f9950

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// ProvideMessage is bean "provideMessage".
	ProvideMessage component.Message
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// ProvideMessage replaces bean "provideMessage".
	ProvideMessage spicebean.Override[component.Message]
}

// BeanOverrideLayer is one named immutable override composition layer.
// Layers are applied in order; a later layer deliberately replaces an earlier value.
type BeanOverrideLayer struct {
	Name      string
	Overrides BeanOverrides
}

// ComposeBeanOverrides validates and deterministically composes named layers.
// It never mutates a running application or performs runtime bean lookup.
func ComposeBeanOverrides(layers ...BeanOverrideLayer) (BeanOverrides, error) {
	result := BeanOverrides{}
	seen := make(map[string]int, len(layers))
	for index, layer := range layers {
		if layer.Name == "" || strings.TrimSpace(layer.Name) != layer.Name {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %d requires a non-empty name without surrounding whitespace", index)
		}
		if previous, duplicate := seen[layer.Name]; duplicate {
			return BeanOverrides{}, fmt.Errorf("compose bean overrides: layer %q repeats layer %d", layer.Name, previous)
		}
		seen[layer.Name] = index
		if layer.Overrides.ProvideMessage.Enabled() {
			result.ProvideMessage = layer.Overrides.ProvideMessage
		}
	}
	return result, nil
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}
