//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	component "example.com/spice-annotation-app/component"
	spiceComponent "example.com/spice-annotation-app/internal/spicegen/spice_annotation_app/sources/component"
	spiceconfig "github.com/StevenBuglione/spice/config"
)

type applicationDependencies struct {
	provideMessage component.Message
}

func constructApplicationDependencies(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
) (*applicationDependencies, error) {
	_ = ctx
	_ = application
	_ = options
	_ = configurationSnapshot
	provideMessage, provideMessageCleanup, err := spiceComponent.ConstructProvideMessage_031f9b83()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct bean provideMessage (example.com/spice-annotation-app/component.Message, source spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage): %w", err))
	}
	if provideMessageCleanup != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage", provideMessageCleanup); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for bean provideMessage (source spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage): %w", err))
		}
	}
	_ = provideMessage
	return &applicationDependencies{
		provideMessage: provideMessage,
	}, nil
}
