//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	flag "flag"
	fmt "fmt"
	io "io"
	slog "log/slog"
	os "os"
	signal "os/signal"
	syscall "syscall"
	time "time"

	component "example.com/spice-annotation-app/component"
	spiceentrypoint "example.com/spice-annotation-app/internal/spicegen/spice_annotation_app/sources/_root"
	spicesource0 "example.com/spice-annotation-app/internal/spicegen/spice_annotation_app/sources/component"
	spiceconfig "github.com/StevenBuglione/spice/config"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

const TargetID = spiceentrypoint.ApplicationTarget064f99508fba

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// ProvideMessage is bean "provideMessage".
	ProvideMessage component.Message
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
}

type ApplicationOptions struct {
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	Observers                 []spicelifecycle.Observer
}

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application spice_annotation_app: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application spice_annotation_app: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application spice_annotation_app: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application spice_annotation_app: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application spice_annotation_app: duration must be positive"))
	}
	provider0, cleanup0, err := spicesource0.Construct031f9b839d45()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage (example.com/spice-annotation-app/component.Message): %w", err))
	}
	if cleanup0 != nil {
		if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage", cleanup0); err != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for provider spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage: %w", err))
		}
	}
	_ = provider0
	application.components = Components{
		ProvideMessage: provider0,
	}
	return application, nil
}

func (application *Application) State() spicelifecycle.State {
	if application == nil || application.coordinator == nil {
		return spicelifecycle.StateInvalid
	}
	return application.coordinator.State()
}

func (application *Application) Start(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("start application: application is nil")
	}
	return application.coordinator.Start(ctx, application.hooks)
}

func (application *Application) Stop(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("stop application: application is nil")
	}
	return application.coordinator.Stop(ctx)
}

func (application *Application) ShutdownTimeout() time.Duration {
	if application == nil {
		return 0
	}
	return application.shutdownTimeout
}

func (application *Application) RegisterObserver(observer spicelifecycle.Observer) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("register lifecycle observer: application is nil")
	}
	return application.coordinator.RegisterObserver(observer)
}

func (application *Application) Run(ctx context.Context, shutdown spicelifecycle.ContextFactory) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("run application: application is nil")
	}
	return application.coordinator.Run(ctx, application.hooks, shutdown)
}

// Components returns a typed snapshot of constructed singleton beans.
func (application *Application) Components() Components {
	if application == nil {
		return Components{}
	}
	return application.components
}

type ShutdownContextFactory func(time.Duration) (context.Context, context.CancelFunc)

type CommandOptions struct {
	Context         context.Context
	Arguments       []string
	Stdout          io.Writer
	Stderr          io.Writer
	Logger          *slog.Logger
	ShutdownTimeout time.Duration
	ShutdownContext ShutdownContextFactory
	Application     ApplicationOptions
}

func Main(arguments []string) int {
	logger := slog.New(slog.NewJSONHandler(os.Stderr, nil))
	environment, err := spiceconfig.OSEnvironment("SPICE_")
	if err != nil {
		logger.Error("Spice command configuration failed", slog.Any("error", err))
		return ExitFailure
	}
	runContext, stopSignals := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stopSignals()
	return RunCommand(CommandOptions{
		Context:   runContext,
		Arguments: arguments,
		Stdout:    os.Stdout,
		Stderr:    os.Stderr,
		Logger:    logger,
		Application: ApplicationOptions{
			Sources: []spiceconfig.Source{environment},
		},
	})
}

func RunCommand(options CommandOptions) int {
	stdout := options.Stdout
	if stdout == nil {
		stdout = io.Discard
	}
	stderr := options.Stderr
	if stderr == nil {
		stderr = io.Discard
	}
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(stderr, nil))
	}
	ctx := options.Context
	if ctx == nil {
		return commandFailure(context.Background(), logger, "Spice command context is nil", nil)
	}
	if options.ShutdownTimeout < 0 {
		return commandFailure(ctx, logger, "Spice shutdown timeout is invalid", nil)
	}

	flags := flag.NewFlagSet(TargetID, flag.ContinueOnError)
	flags.SetOutput(stderr)
	check := flags.Bool("check", false, "construct the generated application and exit")
	if err := flags.Parse(options.Arguments); err != nil {
		logger.ErrorContext(ctx, "Spice command arguments are invalid", slog.Any("error", err))
		return ExitUsage
	}
	if flags.NArg() != 0 {
		if _, err := fmt.Fprintf(stderr, "%s does not accept positional arguments\n", TargetID); err != nil {
			logger.ErrorContext(ctx, "Spice command usage output failed", slog.Any("error", err))
		}
		return ExitUsage
	}

	applicationOptions := options.Application
	logger.InfoContext(ctx, "Spice application constructing", slog.String("application", TargetID))
	application, err := NewApplicationWithOptions(ctx, applicationOptions)
	if err != nil {
		return commandFailure(ctx, logger, "Spice application construction failed", err)
	}

	shutdownTimeout := application.shutdownTimeout
	if options.ShutdownTimeout > 0 {
		shutdownTimeout = options.ShutdownTimeout
	}
	shutdownContext := options.ShutdownContext
	if shutdownContext == nil {
		shutdownContext = func(timeout time.Duration) (context.Context, context.CancelFunc) {
			return context.WithTimeout(context.Background(), timeout)
		}
	}
	shutdown := func() (context.Context, context.CancelFunc) {
		return shutdownContext(shutdownTimeout)
	}

	if *check {
		if err := stopCheckedApplication(application, shutdown); err != nil {
			return commandFailure(ctx, logger, "Spice application check cleanup failed", err)
		}
		if _, err := fmt.Fprintf(stdout, "Spice %s ready.\n", TargetID); err != nil {
			return commandFailure(ctx, logger, "Spice readiness output failed", err)
		}
		return ExitSuccess
	}

	logger.InfoContext(ctx, "Spice application starting", slog.String("application", TargetID))
	if err := application.Run(ctx, shutdown); err != nil {
		return commandFailure(ctx, logger, "Spice application run failed", err)
	}
	logger.InfoContext(context.Background(), "Spice application stopped", slog.String("application", TargetID))
	return ExitSuccess
}

func stopCheckedApplication(
	application *Application,
	shutdown spicelifecycle.ContextFactory,
) error {
	shutdownContext, cancel := shutdown()
	if shutdownContext == nil || cancel == nil {
		return fmt.Errorf("check application: shutdown context factory returned a nil context or cancel function")
	}
	defer cancel()
	return application.Stop(shutdownContext)
}

func commandFailure(
	ctx context.Context,
	logger *slog.Logger,
	message string,
	err error,
) int {
	if err == nil {
		logger.ErrorContext(ctx, message)
	} else {
		logger.ErrorContext(ctx, message, slog.Any("error", err))
	}
	return ExitFailure
}
