//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: main.go:16

package spicegen

// ApplicationTargetSpiceAnnotationApp_064f9950 identifies the generated target selected by spice:symbol:v1|function|32:example.com/spice-annotation-app|0:|4:main.
const ApplicationTargetSpiceAnnotationApp_064f9950 = "spice_annotation_app"
