//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: main.go:16

package spicegen

// ApplicationTarget064f99508fba identifies the generated target selected by spice:symbol:v1|function|32:example.com/spice-annotation-app|0:|4:main.
const ApplicationTarget064f99508fba = "spice_annotation_app"
