//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: system/welcome_controller.go:18

package spicegen

import (
	fmt "fmt"

	system "github.com/StevenBuglione/spice/examples/petclinic/system"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct0b0c501d7cba performs the direct construction selected for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/system|0:|17:WelcomeController.
func Construct0b0c501d7cba(dependency0 *i18n.Catalog) (*system.WelcomeController, spicelifecycle.Cleanup, error) {
	value, err := system.NewWelcomeController(dependency0)
	if err != nil {
		var zero *system.WelcomeController
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/system|0:|17:WelcomeController (*github.com/StevenBuglione/spice/examples/petclinic/system.WelcomeController): %w", err)
	}
	return value, nil, nil
}
