//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: main.go:19

package spicegen

// ApplicationTargetPetclinic_2898e5e7 identifies the generated target selected by spice:symbol:v1|function|50:github.com/StevenBuglione/spice/examples/petclinic|0:|4:main.
const ApplicationTargetPetclinic_2898e5e7 = "petclinic"
