//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: main.go:19

package spicegen

// ApplicationTargetPetclinic_c48ca98e identifies the generated target selected by spice:symbol:v1|function|51:github.com/spice-framework/spice/examples/petclinic|0:|4:main.
const ApplicationTargetPetclinic_c48ca98e = "petclinic"
