//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/database.go:25

package spicegen

import (
	fmt "fmt"

	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Constructfc953d95bba0 performs the direct construction selected for spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|12:OpenDatabase.
func Constructfc953d95bba0(dependency0 mysql.Settings) (*mysql.Database, spicelifecycle.Cleanup, error) {
	value, cleanup, err := mysql.OpenDatabase(dependency0)
	if err != nil {
		var zero *mysql.Database
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|12:OpenDatabase (*github.com/StevenBuglione/spice/examples/petclinic/mysql.Database): %w", err)
	}
	return value, cleanup, nil
}
