//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/owner_repository.go:17

package spicegen

import (
	fmt "fmt"

	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructOwnerRepository_055f5543 performs the direct construction selected for bean "ownerRepository".
// Spice source identity: spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository.
func ConstructOwnerRepository_055f5543(dependency0 *mysql.Database) (*mysql.OwnerRepository, spicelifecycle.Cleanup, error) {
	value, err := mysql.NewOwnerRepository(dependency0)
	if err != nil {
		var zero *mysql.OwnerRepository
		return zero, nil, fmt.Errorf("construct bean ownerRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.OwnerRepository, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsOwnerRepositoryAsRepository_3593c16a verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository.
var spiceImplementsOwnerRepositoryAsRepository_3593c16a owner.Repository = *new(*mysql.OwnerRepository)
