//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/owner_repository.go:17

package spicegen

import (
	fmt "fmt"

	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct055f554318eb performs the direct construction selected for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository.
func Construct055f554318eb(dependency0 *mysql.Database) (*mysql.OwnerRepository, spicelifecycle.Cleanup, error) {
	value, err := mysql.NewOwnerRepository(dependency0)
	if err != nil {
		var zero *mysql.OwnerRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.OwnerRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplements3593c16a667f verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|15:OwnerRepository.
var spiceImplements3593c16a667f owner.Repository = *new(*mysql.OwnerRepository)
