//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/pet_type_repository.go:15

package spicegen

import (
	fmt "fmt"

	mysql "github.com/spice-framework/spice/examples/petclinic/mysql"
	owner "github.com/spice-framework/spice/examples/petclinic/owner"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructPetTypeRepository_54be2407 performs the direct construction selected for bean "petTypeRepository".
// Spice source identity: spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/petclinic/mysql|0:|17:PetTypeRepository.
func ConstructPetTypeRepository_54be2407(dependency0 *mysql.Database) (*mysql.PetTypeRepository, spicelifecycle.Cleanup, error) {
	value, err := mysql.NewPetTypeRepository(dependency0)
	if err != nil {
		var zero *mysql.PetTypeRepository
		return zero, nil, fmt.Errorf("construct bean petTypeRepository (*github.com/spice-framework/spice/examples/petclinic/mysql.PetTypeRepository, source spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/petclinic/mysql|0:|17:PetTypeRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsPetTypeRepositoryAsPetTypeRepository_d5a22df1 identifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/petclinic/mysql|0:|17:PetTypeRepository.
var _ owner.PetTypeRepository = (*mysql.PetTypeRepository)(nil)
