//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/pet_type_repository.go:15

package spicegen

import (
	fmt "fmt"

	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct1ad039a76607 performs the direct construction selected for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository.
func Construct1ad039a76607(dependency0 *mysql.Database) (*mysql.PetTypeRepository, spicelifecycle.Cleanup, error) {
	value, err := mysql.NewPetTypeRepository(dependency0)
	if err != nil {
		var zero *mysql.PetTypeRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.PetTypeRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsda9a4220854d verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository.
var spiceImplementsda9a4220854d owner.PetTypeRepository = *new(*mysql.PetTypeRepository)
