//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/pet_type_repository.go:15

package spicegen

import (
	fmt "fmt"

	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructPetTypeRepository_1ad039a7 performs the direct construction selected for bean "petTypeRepository".
// Spice source identity: spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository.
func ConstructPetTypeRepository_1ad039a7(dependency0 *mysql.Database) (*mysql.PetTypeRepository, spicelifecycle.Cleanup, error) {
	value, err := mysql.NewPetTypeRepository(dependency0)
	if err != nil {
		var zero *mysql.PetTypeRepository
		return zero, nil, fmt.Errorf("construct bean petTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.PetTypeRepository, source spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsPetTypeRepositoryAsPetTypeRepository_da9a4220 verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|17:PetTypeRepository.
var spiceImplementsPetTypeRepositoryAsPetTypeRepository_da9a4220 owner.PetTypeRepository = *new(*mysql.PetTypeRepository)
