//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/settings.go:7

package spicegen

import (
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	mysql "github.com/spice-framework/spice/examples/petclinic/mysql"
)

// BindSettings_d2fe50c5 binds the validated configuration declared by spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/petclinic/mysql|0:|8:Settings.
func BindSettings_d2fe50c5(configurationSnapshot spiceconfig.Snapshot) (mysql.Settings, error) {
	value := mysql.Settings{}
	if _, configured := configurationSnapshot.Lookup("petclinic.datasource.url"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("petclinic.datasource.url")
		if valueErr != nil {
			return mysql.Settings{}, fmt.Errorf("decode configuration property petclinic.datasource.url for github.com/spice-framework/spice/examples/petclinic/mysql.Settings.URL: %w", valueErr)
		}
		convertedValue := string(rawValue)
		value.URL = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("petclinic.datasource.allow-insecure"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("petclinic.datasource.allow-insecure")
		if valueErr != nil {
			return mysql.Settings{}, fmt.Errorf("decode configuration property petclinic.datasource.allow-insecure for github.com/spice-framework/spice/examples/petclinic/mysql.Settings.AllowInsecure: %w", valueErr)
		}
		convertedValue := bool(rawValue)
		value.AllowInsecure = convertedValue
	}
	return value, nil
}
