//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/vet_repository.go:16

package spicegen

import (
	fmt "fmt"

	mysql "github.com/spice-framework/spice/examples/petclinic/mysql"
	vet "github.com/spice-framework/spice/examples/petclinic/vet"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructVetRepository_62df1dd8 performs the direct construction selected for bean "vetRepository".
// Spice source identity: spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/petclinic/mysql|0:|13:VetRepository.
func ConstructVetRepository_62df1dd8(dependency0 *mysql.Database) (*mysql.VetRepository, spicelifecycle.Cleanup, error) {
	value, err := mysql.NewVetRepository(dependency0)
	if err != nil {
		var zero *mysql.VetRepository
		return zero, nil, fmt.Errorf("construct bean vetRepository (*github.com/spice-framework/spice/examples/petclinic/mysql.VetRepository, source spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/petclinic/mysql|0:|13:VetRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsVetRepositoryAsRepository_3550d174 identifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/spice-framework/spice/examples/petclinic/mysql|0:|13:VetRepository.
var _ vet.Repository = (*mysql.VetRepository)(nil)
