//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: mysql/vet_repository.go:16

package spicegen

import (
	fmt "fmt"

	mysql "github.com/StevenBuglione/spice/examples/petclinic/mysql"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Constructe6a8bff43a7b performs the direct construction selected for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|13:VetRepository.
func Constructe6a8bff43a7b(dependency0 *mysql.Database) (*mysql.VetRepository, spicelifecycle.Cleanup, error) {
	value, err := mysql.NewVetRepository(dependency0)
	if err != nil {
		var zero *mysql.VetRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|13:VetRepository (*github.com/StevenBuglione/spice/examples/petclinic/mysql.VetRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplements91b1c4460a3f verifies the explicit @Implements binding for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/mysql|0:|13:VetRepository.
var spiceImplements91b1c4460a3f vet.Repository = *new(*mysql.VetRepository)
