//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: component/message.go:9

package spicegen

import (
	component "example.com/spice-annotation-app/component"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructProvideMessage_031f9b83 performs the direct construction selected for bean "provideMessage".
// Spice source identity: spice:symbol:v1|function|42:example.com/spice-annotation-app/component|0:|14:ProvideMessage.
func ConstructProvideMessage_031f9b83() (component.Message, spicelifecycle.Cleanup, error) {
	value := component.ProvideMessage()
	return value, nil, nil
}
