//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/owner_repository.go:17

package spicegen

import (
	fmt "fmt"

	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructOwnerRepository_2966447b performs the direct construction selected for bean "ownerRepository".
// Spice source identity: spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository.
func ConstructOwnerRepository_2966447b(dependency0 *memory.Database) (*memory.OwnerRepository, spicelifecycle.Cleanup, error) {
	value, err := memory.NewOwnerRepository(dependency0)
	if err != nil {
		var zero *memory.OwnerRepository
		return zero, nil, fmt.Errorf("construct bean ownerRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.OwnerRepository, source spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsOwnerRepositoryAsRepository_f1a2fa85 verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository.
var spiceImplementsOwnerRepositoryAsRepository_f1a2fa85 owner.Repository = *new(*memory.OwnerRepository)
