//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/owner_repository.go:17

package spicegen

import (
	fmt "fmt"

	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct2966447be465 performs the direct construction selected for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository.
func Construct2966447be465(dependency0 *memory.Database) (*memory.OwnerRepository, spicelifecycle.Cleanup, error) {
	value, err := memory.NewOwnerRepository(dependency0)
	if err != nil {
		var zero *memory.OwnerRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.OwnerRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsf1a2fa856981 verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository.
var spiceImplementsf1a2fa856981 owner.Repository = *new(*memory.OwnerRepository)
