//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/owner_repository.go:17

package spicegen

import (
	fmt "fmt"

	memory "github.com/spice-framework/spice/examples/petclinic/memory"
	owner "github.com/spice-framework/spice/examples/petclinic/owner"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructOwnerRepository_0371b4e3 performs the direct construction selected for bean "ownerRepository".
// Spice source identity: spice:symbol:v1|type|58:github.com/spice-framework/spice/examples/petclinic/memory|0:|15:OwnerRepository.
func ConstructOwnerRepository_0371b4e3(dependency0 *memory.Database) (*memory.OwnerRepository, spicelifecycle.Cleanup, error) {
	value, err := memory.NewOwnerRepository(dependency0)
	if err != nil {
		var zero *memory.OwnerRepository
		return zero, nil, fmt.Errorf("construct bean ownerRepository (*github.com/spice-framework/spice/examples/petclinic/memory.OwnerRepository, source spice:symbol:v1|type|58:github.com/spice-framework/spice/examples/petclinic/memory|0:|15:OwnerRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsOwnerRepositoryAsRepository_15e3c972 identifies the explicit @Implements binding for spice:symbol:v1|type|58:github.com/spice-framework/spice/examples/petclinic/memory|0:|15:OwnerRepository.
var _ owner.Repository = (*memory.OwnerRepository)(nil)
