//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/pet_type_repository.go:16

package spicegen

import (
	fmt "fmt"

	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructPetTypeRepository_eaa83bf0 performs the direct construction selected for bean "petTypeRepository".
// Spice source identity: spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository.
func ConstructPetTypeRepository_eaa83bf0(dependency0 *memory.Database) (*memory.PetTypeRepository, spicelifecycle.Cleanup, error) {
	value, err := memory.NewPetTypeRepository(dependency0)
	if err != nil {
		var zero *memory.PetTypeRepository
		return zero, nil, fmt.Errorf("construct bean petTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.PetTypeRepository, source spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsPetTypeRepositoryAsPetTypeRepository_03415e64 verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository.
var spiceImplementsPetTypeRepositoryAsPetTypeRepository_03415e64 owner.PetTypeRepository = *new(*memory.PetTypeRepository)
