//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/pet_type_repository.go:16

package spicegen

import (
	fmt "fmt"

	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Constructeaa83bf0245a performs the direct construction selected for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository.
func Constructeaa83bf0245a(dependency0 *memory.Database) (*memory.PetTypeRepository, spicelifecycle.Cleanup, error) {
	value, err := memory.NewPetTypeRepository(dependency0)
	if err != nil {
		var zero *memory.PetTypeRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.PetTypeRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplements03415e64d85b verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository.
var spiceImplements03415e64d85b owner.PetTypeRepository = *new(*memory.PetTypeRepository)
