//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/seed.go:16

package spicegen

import (
	fmt "fmt"

	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct75fb0ba1ff59 performs the direct construction selected for spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|20:NewPetclinicDatabase.
func Construct75fb0ba1ff59() (*memory.Database, spicelifecycle.Cleanup, error) {
	value, err := memory.NewPetclinicDatabase()
	if err != nil {
		var zero *memory.Database
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|20:NewPetclinicDatabase (*github.com/StevenBuglione/spice/examples/petclinic/memory.Database): %w", err)
	}
	return value, nil, nil
}
