//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/vet_repository.go:16

package spicegen

import (
	fmt "fmt"

	memory "github.com/spice-framework/spice/examples/petclinic/memory"
	vet "github.com/spice-framework/spice/examples/petclinic/vet"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructVetRepository_5625e0ef performs the direct construction selected for bean "vetRepository".
// Spice source identity: spice:symbol:v1|type|58:github.com/spice-framework/spice/examples/petclinic/memory|0:|13:VetRepository.
func ConstructVetRepository_5625e0ef(dependency0 *memory.Database) (*memory.VetRepository, spicelifecycle.Cleanup, error) {
	value, err := memory.NewVetRepository(dependency0)
	if err != nil {
		var zero *memory.VetRepository
		return zero, nil, fmt.Errorf("construct bean vetRepository (*github.com/spice-framework/spice/examples/petclinic/memory.VetRepository, source spice:symbol:v1|type|58:github.com/spice-framework/spice/examples/petclinic/memory|0:|13:VetRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsVetRepositoryAsRepository_c9ce5770 identifies the explicit @Implements binding for spice:symbol:v1|type|58:github.com/spice-framework/spice/examples/petclinic/memory|0:|13:VetRepository.
var _ vet.Repository = (*memory.VetRepository)(nil)
