//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/vet_repository.go:16

package spicegen

import (
	fmt "fmt"

	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct3a6aad84dbc1 performs the direct construction selected for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|13:VetRepository.
func Construct3a6aad84dbc1(dependency0 *memory.Database) (*memory.VetRepository, spicelifecycle.Cleanup, error) {
	value, err := memory.NewVetRepository(dependency0)
	if err != nil {
		var zero *memory.VetRepository
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|13:VetRepository (*github.com/StevenBuglione/spice/examples/petclinic/memory.VetRepository): %w", err)
	}
	return value, nil, nil
}

// spiceImplementsf75617ef7566 verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|13:VetRepository.
var spiceImplementsf75617ef7566 vet.Repository = *new(*memory.VetRepository)
