//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: presentation/server.go:31

package spicegen

import (
	fmt "fmt"
	http "net/http"

	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct2f66240e3f13 performs the direct construction selected for spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer.
func Construct2f66240e3f13(dependency0 presentation.ServerSettings, dependency1 *http.ServeMux) (*presentation.Server, spicelifecycle.Cleanup, error) {
	value, err := presentation.NewServer(dependency0, dependency1)
	if err != nil {
		var zero *presentation.Server
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer (*github.com/StevenBuglione/spice/examples/petclinic/presentation.Server): %w", err)
	}
	return value, nil, nil
}
