//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: cmd/postgres/main.go:18

package spicegen

// ApplicationTargetPostgres_510ed9a8 identifies the generated target selected by spice:symbol:v1|function|64:github.com/spice-framework/spice/examples/petclinic/cmd/postgres|0:|4:main.
const ApplicationTargetPostgres_510ed9a8 = "postgres"
