//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: cmd/postgres/main.go:18

package spicegen

// ApplicationTargetPostgres_6bc99d88 identifies the generated target selected by spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/cmd/postgres|0:|4:main.
const ApplicationTargetPostgres_6bc99d88 = "postgres"
