//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: owner/controller.go:25

package spicegen

import (
	fmt "fmt"

	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct6d9e55b64a8b performs the direct construction selected for spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|10:Controller.
func Construct6d9e55b64a8b(dependency0 owner.Repository, dependency1 *i18n.Catalog) (*owner.Controller, spicelifecycle.Cleanup, error) {
	value, err := owner.NewController(dependency0, dependency1)
	if err != nil {
		var zero *owner.Controller
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|10:Controller (*github.com/StevenBuglione/spice/examples/petclinic/owner.Controller): %w", err)
	}
	return value, nil, nil
}
