//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: presentation/catalog.go:16

package spicegen

import (
	fmt "fmt"

	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// ConstructCatalog_6e1785b3 performs the direct construction selected for bean "newCatalog".
// Spice source identity: spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|10:NewCatalog.
func ConstructCatalog_6e1785b3() (*i18n.Catalog, spicelifecycle.Cleanup, error) {
	value, err := presentation.NewCatalog()
	if err != nil {
		var zero *i18n.Catalog
		return zero, nil, fmt.Errorf("construct bean newCatalog (*github.com/StevenBuglione/spice/i18n.Catalog, source spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|10:NewCatalog): %w", err)
	}
	return value, nil, nil
}
