//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: presentation/mux.go:11

package spicegen

import (
	fmt "fmt"
	http "net/http"

	presentation "github.com/spice-framework/spice/examples/petclinic/presentation"
	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

// ConstructMux_c4b2b961 performs the direct construction selected for bean "newMux".
// Spice source identity: spice:symbol:v1|function|64:github.com/spice-framework/spice/examples/petclinic/presentation|0:|6:NewMux.
func ConstructMux_c4b2b961() (*http.ServeMux, spicelifecycle.Cleanup, error) {
	value, err := presentation.NewMux()
	if err != nil {
		var zero *http.ServeMux
		return zero, nil, fmt.Errorf("construct bean newMux (*net/http.ServeMux, source spice:symbol:v1|function|64:github.com/spice-framework/spice/examples/petclinic/presentation|0:|6:NewMux): %w", err)
	}
	return value, nil, nil
}
