//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: presentation/mux.go:11

package spicegen

import (
	fmt "fmt"
	http "net/http"

	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
)

// Construct1ec2a68a9590 performs the direct construction selected for spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|6:NewMux.
func Construct1ec2a68a9590() (*http.ServeMux, spicelifecycle.Cleanup, error) {
	value, err := presentation.NewMux()
	if err != nil {
		var zero *http.ServeMux
		return zero, nil, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|6:NewMux (*net/http.ServeMux): %w", err)
	}
	return value, nil, nil
}
