//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceconfig "github.com/StevenBuglione/spice/config"
	spicemanagement "github.com/StevenBuglione/spice/management"
	spiceweb "github.com/StevenBuglione/spice/web"
)

func configureGeneratedHTTP(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSchema spiceconfig.Schema,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	managementMetrics *spicemanagement.HTTPMetrics,
) (*Application, error) {
	_ = configurationSchema
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeMux := dependencies.provider2
	application.mux = routeMux
	application.handler = routeMux
	if _, err := registerGeneratedRoute5badfbece45c(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouted306b13c6a4b(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute49afddd06269(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouted73d965f3f4b(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteebdcb72a1c6d(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteb5b989aec353(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute7455f8a2cde9(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute92cf9af698cf(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute85d595d32bb4(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute9df899efc147(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouted35ff46f5f41(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute55f9d3e7faa6(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute4692814b13b8(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute415f0e672062(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute6208272f914d(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRoute94e120b72418(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	managementChecks, err := spicemanagement.LifecycleChecks(TargetID, "github.com/StevenBuglione/spice/examples/petclinic/cmd/postgres", application.State)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management lifecycle checks: %w", err))
	}
	managementManager, err := spicemanagement.New(managementChecks...)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management checks: %w", err))
	}
	managementConfiguration, err := spicemanagement.NewConfigurationReport(configurationSchema, configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management configuration report: %w", err))
	}
	managementModules, err := spicemanagement.NewModuleReport(
		[]spicemanagement.ModuleDefinition{},
		[]spicemanagement.ModuleEdge{},
		[]string{},
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management module report: %w", err))
	}
	managementHandler, err := spicemanagement.NewHandler(spicemanagement.HandlerOptions{
		Manager: managementManager,
		Info: map[string]string{
			"application": TargetID,
			"module":      "github.com/StevenBuglione/spice/examples/petclinic/cmd/postgres",
			"framework":   "Spice",
		},
		Metrics:       managementMetrics,
		Configuration: &managementConfiguration,
		Modules:       &managementModules,
		Expose: []spicemanagement.Endpoint{
			spicemanagement.EndpointConfigProps,
			spicemanagement.EndpointHealth,
			spicemanagement.EndpointInfo,
			spicemanagement.EndpointLiveness,
			spicemanagement.EndpointMetrics,
			spicemanagement.EndpointModules,
			spicemanagement.EndpointReadiness,
		},
		Access: spicemanagement.Access("loopback"),
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management handler: %w", err))
	}
	if err := spiceweb.Register(routeMux, managementHandler.Pattern(), managementHandler); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register management routes: %w", err))
	}
	return application, nil
}
