//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"

	spiceconfig "github.com/spice-framework/spice/config"
	spicemanagement "github.com/spice-framework/spice/management"
	spiceweb "github.com/spice-framework/spice/web"
)

func configureGeneratedHTTP(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSchema spiceconfig.Schema,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	managementMetrics *spicemanagement.HTTPMetrics,
) (*Application, error) {
	_ = configurationSchema
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeMux := dependencies.mux
	application.mux = routeMux
	application.handler = routeMux
	if _, err := registerGeneratedRouteVetControllerListJSON_bbf7ac05(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteVetControllerListHTML_4eb81548(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerFind_2cd5c768(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerFindForm_554d4e3a(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerNewForm_e4501169(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerShow_8423e933(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerEditForm_34933d55(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerCreate_e8591fe8(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerControllerUpdate_9ba33272(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerNewForm_30d451cf(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerEditForm_cd4d645a(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerCreate_8c47f4bf(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerPetControllerUpdate_53ee21b4(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerVisitControllerNewForm_d5f9687d(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteOwnerVisitControllerCreate_f62250e8(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	if _, err := registerGeneratedRouteSystemWelcomeControllerShow_51a573a3(
		ctx,
		application,
		options,
		configurationSnapshot,
		dependencies,
		httpObservers,
		routeMux,
	); err != nil {
		return nil, err
	}
	managementChecks, err := spicemanagement.LifecycleChecks(TargetID, "github.com/spice-framework/spice/examples/petclinic/cmd/postgres", application.State)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management lifecycle checks: %w", err))
	}
	managementManager, err := spicemanagement.New(managementChecks...)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management checks: %w", err))
	}
	managementConfiguration, err := spicemanagement.NewConfigurationReport(configurationSchema, configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management configuration report: %w", err))
	}
	managementModules, err := spicemanagement.NewModuleReport(
		[]spicemanagement.ModuleDefinition{},
		[]spicemanagement.ModuleEdge{},
		[]string{},
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management module report: %w", err))
	}
	managementHandler, err := spicemanagement.NewHandler(spicemanagement.HandlerOptions{
		Manager: managementManager,
		Info: map[string]string{
			"application": TargetID,
			"module":      "github.com/spice-framework/spice/examples/petclinic/cmd/postgres",
			"framework":   "Spice",
		},
		Metrics:       managementMetrics,
		Configuration: &managementConfiguration,
		Modules:       &managementModules,
		Expose: []spicemanagement.Endpoint{
			spicemanagement.EndpointConfigProps,
			spicemanagement.EndpointHealth,
			spicemanagement.EndpointInfo,
			spicemanagement.EndpointLiveness,
			spicemanagement.EndpointMetrics,
			spicemanagement.EndpointModules,
			spicemanagement.EndpointReadiness,
		},
		Access: spicemanagement.Access("loopback"),
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management handler: %w", err))
	}
	if err := spiceweb.Register(routeMux, managementHandler.Pattern(), managementHandler); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register management routes: %w", err))
	}
	return application, nil
}
