//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/spice-framework/spice/config"
	owner "github.com/spice-framework/spice/examples/petclinic/owner"
	spiceview "github.com/spice-framework/spice/view"
	spiceweb "github.com/spice-framework/spice/web"
)

func registerGeneratedRouteOwnerControllerUpdate_9ba33272(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	routeMux *http.ServeMux,
) (*Application, error) {
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|57:github.com/spice-framework/spice/examples/petclinic/owner|10:Controller|6:Update", Module: "", Method: "POST", Pattern: "/owners/{ownerId}/edit"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/{ownerId}/edit observation: %w", routeObservationErr0))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/{ownerId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return dependencies.renderer.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.EditOwnerRequest{}
		bindingResult := spiceweb.BindingResult{}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"firstName", "lastName", "address", "city", "telephone"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		raw2, present2, bindErr2 := spiceweb.FormValue(formValues, "firstName", true)
		if bindErr2 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr2)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present2 {
			requestValue.FirstName = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "lastName", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.LastName = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "address", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			requestValue.Address = string(raw4)
		}
		raw5, present5, bindErr5 := spiceweb.FormValue(formValues, "city", true)
		if bindErr5 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr5)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present5 {
			requestValue.City = string(raw5)
		}
		raw6, present6, bindErr6 := spiceweb.FormValue(formValues, "telephone", true)
		if bindErr6 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr6)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present6 {
			requestValue.Telephone = string(raw6)
		}
		responseValue, routeErr := dependencies.ownerController.Update(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = dependencies.renderer.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/{ownerId}/edit: %w", routeErr))
	}
	return application, nil
}
