// Code generated by Spice. DO NOT EDIT.
//go:build !spice_generate

package spicegen

import (
	context "context"
	flag "flag"
	fmt "fmt"
	io "io"
	slog "log/slog"
	http "net/http"
	os "os"
	signal "os/signal"
	syscall "syscall"
	time "time"

	spiceconfig "github.com/StevenBuglione/spice/config"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	postgres "github.com/StevenBuglione/spice/examples/petclinic/postgres"
	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	system "github.com/StevenBuglione/spice/examples/petclinic/system"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spicemanagement "github.com/StevenBuglione/spice/management"
	spiceobservability "github.com/StevenBuglione/spice/observability"
	spiceview "github.com/StevenBuglione/spice/view"
	spiceweb "github.com/StevenBuglione/spice/web"
)

const TargetID = "postgres"

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// Catalog is bean "newCatalog".
	Catalog *i18n.Catalog
	// Renderer is bean "newRenderer".
	Renderer *spiceview.Renderer
	// Mux is bean "newMux".
	Mux *http.ServeMux
	// WelcomeController is bean "welcomeController".
	WelcomeController *system.WelcomeController
	// Settings is bean "Settings".
	Settings postgres.Settings
	// OpenDatabase is bean "openDatabase".
	OpenDatabase *postgres.Database
	// VetRepository is bean "vetRepository".
	VetRepository *postgres.VetRepository
	// VetController is bean "controller".
	VetController *vet.Controller
	// OwnerRepository is bean "ownerRepository".
	OwnerRepository *postgres.OwnerRepository
	// OwnerController is bean "controller".
	OwnerController *owner.Controller
	// VisitController is bean "visitController".
	VisitController *owner.VisitController
	// PetTypeRepository is bean "petTypeRepository".
	PetTypeRepository *postgres.PetTypeRepository
	// PetController is bean "petController".
	PetController *owner.PetController
	// ServerSettings is bean "ServerSettings".
	ServerSettings presentation.ServerSettings
	// Server is bean "newServer".
	Server *presentation.Server
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
	mux             *http.ServeMux
	handler         http.Handler
}

type ApplicationOptions struct {
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	ErrorMapper               spiceweb.ErrorMapper
	MaxRequestBodyBytes       int64
	HTTPObservers             []spiceweb.HTTPObserver
	Middleware                []spiceweb.Middleware
	Logger                    *slog.Logger
	Observers                 []spicelifecycle.Observer
}

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "petclinic.datasource.url",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_PETCLINIC_POSTGRES_URL",
			Required:    true,
			Secret:      true,
		},
		spiceconfig.Property{
			Key:         "petclinic.datasource.allow-insecure",
			Kind:        spiceconfig.KindBoolean,
			Environment: "SPICE_PETCLINIC_POSTGRES_ALLOW_INSECURE",
			Default:     "false",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:         "petclinic.server.address",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_PETCLINIC_ADDRESS",
			Default:     "127.0.0.1:8080",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.read-header-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "5s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.read-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "15s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.write-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "15s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.idle-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "60s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}

func NewApplication(ctx context.Context, observers ...spicelifecycle.Observer) (*Application, error) {
	return NewApplicationWithOptions(ctx, ApplicationOptions{Observers: observers})
}

func NewApplicationWithOptions(ctx context.Context, options ApplicationOptions) (*Application, error) {
	if ctx == nil {
		return nil, fmt.Errorf("construct application postgres: context is nil")
	}
	application := &Application{coordinator: spicelifecycle.NewCoordinator()}
	observers := append([]spicelifecycle.Observer(nil), options.Observers...)
	httpObservers := append([]spiceweb.HTTPObserver(nil), options.HTTPObservers...)
	_ = httpObservers
	managementMetrics := spicemanagement.NewHTTPMetrics()
	httpObservers = append([]spiceweb.HTTPObserver{managementMetrics}, httpObservers...)
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(os.Stderr, nil))
	}
	lifecycleLogs, err := spiceobservability.NewSlogLifecycleObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure lifecycle logging: %w", err))
	}
	observers = append([]spicelifecycle.Observer{lifecycleLogs}, observers...)
	httpLogs, err := spiceobservability.NewSlogHTTPObserver(logger)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure HTTP logging: %w", err))
	}
	httpObservers = append(httpObservers[:1], append([]spiceweb.HTTPObserver{httpLogs}, httpObservers[1:]...)...)
	for index, observer := range observers {
		if err := application.coordinator.RegisterObserver(observer); err != nil {
			return nil, fmt.Errorf("register lifecycle observer %d: %w", index, err)
		}
	}
	configurationSchema, err := ConfigurationSchema()
	if err != nil {
		return nil, fmt.Errorf("construct configuration schema for application postgres: %w", err)
	}
	configurationSnapshot, err := spiceconfig.Resolve(
		ctx,
		configurationSchema,
		spiceconfig.Options{
			Profiles:     options.Profiles,
			AllowUnknown: options.AllowUnknownConfiguration,
		},
		options.Sources...,
	)
	if err != nil {
		return nil, fmt.Errorf("resolve configuration for application postgres: %w", err)
	}
	application.shutdownTimeout, err = configurationSnapshot.Duration("spice.shutdown-timeout")
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application postgres: %w", err))
	}
	if application.shutdownTimeout <= 0 {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode shutdown timeout for application postgres: duration must be positive"))
	}
	provider0, err := presentation.NewCatalog()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|10:NewCatalog (*github.com/StevenBuglione/spice/i18n.Catalog): %w", err))
	}
	_ = provider0
	provider1, err := presentation.NewRenderer(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|11:NewRenderer (*github.com/StevenBuglione/spice/view.Renderer): %w", err))
	}
	_ = provider1
	provider2, err := presentation.NewMux()
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|6:NewMux (*net/http.ServeMux): %w", err))
	}
	_ = provider2
	provider3, err := system.NewWelcomeController(provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/system|0:|17:WelcomeController (*github.com/StevenBuglione/spice/examples/petclinic/system.WelcomeController): %w", err))
	}
	_ = provider3
	provider4 := postgres.Settings{}
	if _, configured := configurationSnapshot.Lookup("petclinic.datasource.url"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("petclinic.datasource.url")
		if valueErr != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode configuration property petclinic.datasource.url for github.com/StevenBuglione/spice/examples/petclinic/postgres.Settings.URL: %w", valueErr))
		}
		convertedValue := string(rawValue)
		provider4.URL = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("petclinic.datasource.allow-insecure"); configured {
		rawValue, valueErr := configurationSnapshot.Boolean("petclinic.datasource.allow-insecure")
		if valueErr != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode configuration property petclinic.datasource.allow-insecure for github.com/StevenBuglione/spice/examples/petclinic/postgres.Settings.AllowInsecure: %w", valueErr))
		}
		convertedValue := bool(rawValue)
		provider4.AllowInsecure = convertedValue
	}
	_ = provider4
	provider5, cleanup5, err := postgres.OpenDatabase(provider4)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|12:OpenDatabase (*github.com/StevenBuglione/spice/examples/petclinic/postgres.Database): %w", err))
	}
	if err := application.coordinator.RegisterModuleCleanup("", "spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|12:OpenDatabase", cleanup5); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register cleanup for provider spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|12:OpenDatabase: %w", err))
	}
	_ = provider5
	provider6, err := postgres.NewVetRepository(provider5)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|13:VetRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.VetRepository): %w", err))
	}
	_ = provider6
	provider7, err := vet.NewController(provider6, provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|54:github.com/StevenBuglione/spice/examples/petclinic/vet|0:|10:Controller (*github.com/StevenBuglione/spice/examples/petclinic/vet.Controller): %w", err))
	}
	_ = provider7
	provider8, err := postgres.NewOwnerRepository(provider5)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|15:OwnerRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.OwnerRepository): %w", err))
	}
	_ = provider8
	provider9, err := owner.NewController(provider8, provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|10:Controller (*github.com/StevenBuglione/spice/examples/petclinic/owner.Controller): %w", err))
	}
	_ = provider9
	provider10, err := owner.NewVisitController(provider8, provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|15:VisitController (*github.com/StevenBuglione/spice/examples/petclinic/owner.VisitController): %w", err))
	}
	_ = provider10
	provider11, err := postgres.NewPetTypeRepository(provider5)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|17:PetTypeRepository (*github.com/StevenBuglione/spice/examples/petclinic/postgres.PetTypeRepository): %w", err))
	}
	_ = provider11
	provider12, err := owner.NewPetController(provider8, provider11, provider0)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|type|56:github.com/StevenBuglione/spice/examples/petclinic/owner|0:|13:PetController (*github.com/StevenBuglione/spice/examples/petclinic/owner.PetController): %w", err))
	}
	_ = provider12
	provider13 := presentation.ServerSettings{}
	if _, configured := configurationSnapshot.Lookup("petclinic.server.address"); configured {
		rawValue, valueErr := configurationSnapshot.RequiredString("petclinic.server.address")
		if valueErr != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode configuration property petclinic.server.address for github.com/StevenBuglione/spice/examples/petclinic/presentation.ServerSettings.Address: %w", valueErr))
		}
		convertedValue := string(rawValue)
		provider13.Address = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("petclinic.server.read-header-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("petclinic.server.read-header-timeout")
		if valueErr != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode configuration property petclinic.server.read-header-timeout for github.com/StevenBuglione/spice/examples/petclinic/presentation.ServerSettings.ReadHeaderTimeout: %w", valueErr))
		}
		convertedValue := time.Duration(rawValue)
		provider13.ReadHeaderTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("petclinic.server.read-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("petclinic.server.read-timeout")
		if valueErr != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode configuration property petclinic.server.read-timeout for github.com/StevenBuglione/spice/examples/petclinic/presentation.ServerSettings.ReadTimeout: %w", valueErr))
		}
		convertedValue := time.Duration(rawValue)
		provider13.ReadTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("petclinic.server.write-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("petclinic.server.write-timeout")
		if valueErr != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode configuration property petclinic.server.write-timeout for github.com/StevenBuglione/spice/examples/petclinic/presentation.ServerSettings.WriteTimeout: %w", valueErr))
		}
		convertedValue := time.Duration(rawValue)
		provider13.WriteTimeout = convertedValue
	}
	if _, configured := configurationSnapshot.Lookup("petclinic.server.idle-timeout"); configured {
		rawValue, valueErr := configurationSnapshot.Duration("petclinic.server.idle-timeout")
		if valueErr != nil {
			return nil, application.coordinator.Abort(ctx, fmt.Errorf("decode configuration property petclinic.server.idle-timeout for github.com/StevenBuglione/spice/examples/petclinic/presentation.ServerSettings.IdleTimeout: %w", valueErr))
		}
		convertedValue := time.Duration(rawValue)
		provider13.IdleTimeout = convertedValue
	}
	_ = provider13
	provider14, err := presentation.NewServer(provider13, provider2)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct provider spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer (*github.com/StevenBuglione/spice/examples/petclinic/presentation.Server): %w", err))
	}
	_ = provider14
	application.components = Components{
		Catalog:           provider0,
		Renderer:          provider1,
		Mux:               provider2,
		WelcomeController: provider3,
		Settings:          provider4,
		OpenDatabase:      provider5,
		VetRepository:     provider6,
		VetController:     provider7,
		OwnerRepository:   provider8,
		OwnerController:   provider9,
		VisitController:   provider10,
		PetTypeRepository: provider11,
		PetController:     provider12,
		ServerSettings:    provider13,
		Server:            provider14,
	}
	routeMux := provider2
	application.mux = routeMux
	application.handler = routeMux
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|54:github.com/StevenBuglione/spice/examples/petclinic/vet|10:Controller|8:ListJSON", Module: "", Method: "GET", Pattern: "/vets"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /vets observation: %w", routeObservationErr0))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /vets", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return spiceweb.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceweb.AcceptsJSON(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces application/json",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := vet.AllRequest{}
		responseValue, routeErr := provider7.ListJSON(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = spiceweb.WriteJSON(writer, http.StatusOK, responseValue)
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /vets: %w", routeErr))
	}
	routeObservation1, routeObservationErr1 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|54:github.com/StevenBuglione/spice/examples/petclinic/vet|10:Controller|8:ListHTML", Module: "", Method: "GET", Pattern: "/vets.html"}, httpObservers...)
	if routeObservationErr1 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /vets.html observation: %w", routeObservationErr1))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /vets.html", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := vet.ListRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationQuery, "page", httpRequest.URL.Query()["page"], false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationQuery, "page", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.Page = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		responseValue, routeErr := provider7.ListHTML(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation1, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /vets.html: %w", routeErr))
	}
	routeObservation2, routeObservationErr2 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|4:Find", Module: "", Method: "GET", Pattern: "/owners"}, httpObservers...)
	if routeObservationErr2 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners observation: %w", routeObservationErr2))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.FindOwnersRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationQuery, "lastName", httpRequest.URL.Query()["lastName"], false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			requestValue.LastName = string(raw0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationQuery, "page", httpRequest.URL.Query()["page"], false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			parsed1, parseErr1 := spiceweb.Integer(spiceweb.LocationQuery, "page", raw1, 0)
			if parseErr1 != nil {
				_ = writeRouteError(parseErr1)
				return
			}
			requestValue.Page = int(parsed1)
		}
		raw2, present2, bindErr2 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr2 != nil {
			_ = writeRouteError(bindErr2)
			return
		}
		if present2 {
			requestValue.Language = string(raw2)
		}
		responseValue, routeErr := provider9.Find(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation2, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners: %w", routeErr))
	}
	routeObservation3, routeObservationErr3 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|8:FindForm", Module: "", Method: "GET", Pattern: "/owners/find"}, httpObservers...)
	if routeObservationErr3 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/find observation: %w", routeObservationErr3))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/find", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.FindOwnerFormRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			requestValue.Language = string(raw0)
		}
		responseValue, routeErr := provider9.FindForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation3, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/find: %w", routeErr))
	}
	routeObservation4, routeObservationErr4 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|7:NewForm", Module: "", Method: "GET", Pattern: "/owners/new"}, httpObservers...)
	if routeObservationErr4 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/new observation: %w", routeObservationErr4))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.NewOwnerRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			requestValue.Language = string(raw0)
		}
		responseValue, routeErr := provider9.NewForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation4, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/new: %w", routeErr))
	}
	routeObservation5, routeObservationErr5 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|4:Show", Module: "", Method: "GET", Pattern: "/owners/{ownerId}"}, httpObservers...)
	if routeObservationErr5 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId} observation: %w", routeObservationErr5))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.OwnerIDRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		responseValue, routeErr := provider9.Show(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation5, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}: %w", routeErr))
	}
	routeObservation6, routeObservationErr6 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|8:EditForm", Module: "", Method: "GET", Pattern: "/owners/{ownerId}/edit"}, httpObservers...)
	if routeObservationErr6 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId}/edit observation: %w", routeObservationErr6))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.OwnerIDRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		responseValue, routeErr := provider9.EditForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation6, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}/edit: %w", routeErr))
	}
	routeObservation7, routeObservationErr7 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|6:Create", Module: "", Method: "POST", Pattern: "/owners/new"}, httpObservers...)
	if routeObservationErr7 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/new observation: %w", routeObservationErr7))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.OwnerFormRequest{}
		bindingResult := spiceweb.BindingResult{}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"firstName", "lastName", "address", "city", "telephone"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			requestValue.Language = string(raw0)
		}
		raw1, present1, bindErr1 := spiceweb.FormValue(formValues, "firstName", true)
		if bindErr1 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr1)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present1 {
			requestValue.FirstName = string(raw1)
		}
		raw2, present2, bindErr2 := spiceweb.FormValue(formValues, "lastName", true)
		if bindErr2 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr2)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present2 {
			requestValue.LastName = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "address", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.Address = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "city", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			requestValue.City = string(raw4)
		}
		raw5, present5, bindErr5 := spiceweb.FormValue(formValues, "telephone", true)
		if bindErr5 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr5)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present5 {
			requestValue.Telephone = string(raw5)
		}
		responseValue, routeErr := provider9.Create(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation7, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/new: %w", routeErr))
	}
	routeObservation8, routeObservationErr8 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|6:Update", Module: "", Method: "POST", Pattern: "/owners/{ownerId}/edit"}, httpObservers...)
	if routeObservationErr8 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/{ownerId}/edit observation: %w", routeObservationErr8))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/{ownerId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.EditOwnerRequest{}
		bindingResult := spiceweb.BindingResult{}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"firstName", "lastName", "address", "city", "telephone"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		raw2, present2, bindErr2 := spiceweb.FormValue(formValues, "firstName", true)
		if bindErr2 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr2)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present2 {
			requestValue.FirstName = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "lastName", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.LastName = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "address", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			requestValue.Address = string(raw4)
		}
		raw5, present5, bindErr5 := spiceweb.FormValue(formValues, "city", true)
		if bindErr5 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr5)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present5 {
			requestValue.City = string(raw5)
		}
		raw6, present6, bindErr6 := spiceweb.FormValue(formValues, "telephone", true)
		if bindErr6 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr6)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present6 {
			requestValue.Telephone = string(raw6)
		}
		responseValue, routeErr := provider9.Update(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation8, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/{ownerId}/edit: %w", routeErr))
	}
	routeObservation9, routeObservationErr9 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|13:PetController|7:NewForm", Module: "", Method: "GET", Pattern: "/owners/{ownerId}/pets/new"}, httpObservers...)
	if routeObservationErr9 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId}/pets/new observation: %w", routeObservationErr9))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}/pets/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.NewPetRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		responseValue, routeErr := provider12.NewForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation9, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}/pets/new: %w", routeErr))
	}
	routeObservation10, routeObservationErr10 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|13:PetController|8:EditForm", Module: "", Method: "GET", Pattern: "/owners/{ownerId}/pets/{petId}/edit"}, httpObservers...)
	if routeObservationErr10 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId}/pets/{petId}/edit observation: %w", routeObservationErr10))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}/pets/{petId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.OwnerPetRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationPath, "petId", []string{httpRequest.PathValue("petId")}, true)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			parsed1, parseErr1 := spiceweb.Integer(spiceweb.LocationPath, "petId", raw1, 0)
			if parseErr1 != nil {
				_ = writeRouteError(parseErr1)
				return
			}
			requestValue.PetID = int(parsed1)
		}
		raw2, present2, bindErr2 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr2 != nil {
			_ = writeRouteError(bindErr2)
			return
		}
		if present2 {
			requestValue.Language = string(raw2)
		}
		responseValue, routeErr := provider12.EditForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation10, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}/pets/{petId}/edit: %w", routeErr))
	}
	routeObservation11, routeObservationErr11 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|13:PetController|6:Create", Module: "", Method: "POST", Pattern: "/owners/{ownerId}/pets/new"}, httpObservers...)
	if routeObservationErr11 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/{ownerId}/pets/new observation: %w", routeObservationErr11))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/{ownerId}/pets/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.PetFormRequest{}
		bindingResult := spiceweb.BindingResult{}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"name", "birthDate", "type"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		raw2, present2, bindErr2 := spiceweb.FormValue(formValues, "name", true)
		if bindErr2 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr2)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present2 {
			requestValue.Name = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "birthDate", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.BirthDate = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "type", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			parsed4, parseErr4 := spiceweb.Integer(spiceweb.LocationForm, "type", raw4, 0)
			if parseErr4 != nil {
				updatedBindingResult, rejectErr := bindingResult.RejectBinding(parseErr4)
				if rejectErr != nil {
					_ = writeRouteError(rejectErr)
					return
				}
				bindingResult = updatedBindingResult
			} else {
				requestValue.TypeID = int(parsed4)
			}
		}
		responseValue, routeErr := provider12.Create(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation11, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/{ownerId}/pets/new: %w", routeErr))
	}
	routeObservation12, routeObservationErr12 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|13:PetController|6:Update", Module: "", Method: "POST", Pattern: "/owners/{ownerId}/pets/{petId}/edit"}, httpObservers...)
	if routeObservationErr12 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/{ownerId}/pets/{petId}/edit observation: %w", routeObservationErr12))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/{ownerId}/pets/{petId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.EditPetRequest{}
		bindingResult := spiceweb.BindingResult{}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"name", "birthDate", "type"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationPath, "petId", []string{httpRequest.PathValue("petId")}, true)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			parsed1, parseErr1 := spiceweb.Integer(spiceweb.LocationPath, "petId", raw1, 0)
			if parseErr1 != nil {
				_ = writeRouteError(parseErr1)
				return
			}
			requestValue.PetID = int(parsed1)
		}
		raw2, present2, bindErr2 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr2 != nil {
			_ = writeRouteError(bindErr2)
			return
		}
		if present2 {
			requestValue.Language = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "name", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.Name = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "birthDate", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			requestValue.BirthDate = string(raw4)
		}
		raw5, present5, bindErr5 := spiceweb.FormValue(formValues, "type", true)
		if bindErr5 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr5)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present5 {
			parsed5, parseErr5 := spiceweb.Integer(spiceweb.LocationForm, "type", raw5, 0)
			if parseErr5 != nil {
				updatedBindingResult, rejectErr := bindingResult.RejectBinding(parseErr5)
				if rejectErr != nil {
					_ = writeRouteError(rejectErr)
					return
				}
				bindingResult = updatedBindingResult
			} else {
				requestValue.TypeID = int(parsed5)
			}
		}
		responseValue, routeErr := provider12.Update(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation12, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/{ownerId}/pets/{petId}/edit: %w", routeErr))
	}
	routeObservation13, routeObservationErr13 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|15:VisitController|7:NewForm", Module: "", Method: "GET", Pattern: "/owners/{ownerId}/pets/{petId}/visits/new"}, httpObservers...)
	if routeObservationErr13 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId}/pets/{petId}/visits/new observation: %w", routeObservationErr13))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}/pets/{petId}/visits/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.NewVisitRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationPath, "petId", []string{httpRequest.PathValue("petId")}, true)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			parsed1, parseErr1 := spiceweb.Integer(spiceweb.LocationPath, "petId", raw1, 0)
			if parseErr1 != nil {
				_ = writeRouteError(parseErr1)
				return
			}
			requestValue.PetID = int(parsed1)
		}
		raw2, present2, bindErr2 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr2 != nil {
			_ = writeRouteError(bindErr2)
			return
		}
		if present2 {
			requestValue.Language = string(raw2)
		}
		responseValue, routeErr := provider10.NewForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation13, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}/pets/{petId}/visits/new: %w", routeErr))
	}
	routeObservation14, routeObservationErr14 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|15:VisitController|6:Create", Module: "", Method: "POST", Pattern: "/owners/{ownerId}/pets/{petId}/visits/new"}, httpObservers...)
	if routeObservationErr14 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route POST /owners/{ownerId}/pets/{petId}/visits/new observation: %w", routeObservationErr14))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "POST /owners/{ownerId}/pets/{petId}/visits/new", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.VisitFormRequest{}
		bindingResult := spiceweb.BindingResult{}
		formValues, formErr := spiceweb.DecodeForm(httpRequest, options.MaxRequestBodyBytes)
		if formErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(formErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if unknownFormErr := spiceweb.RejectUnknownForm(formValues, []string{"date", "description"}); unknownFormErr != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(unknownFormErr)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationPath, "petId", []string{httpRequest.PathValue("petId")}, true)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			parsed1, parseErr1 := spiceweb.Integer(spiceweb.LocationPath, "petId", raw1, 0)
			if parseErr1 != nil {
				_ = writeRouteError(parseErr1)
				return
			}
			requestValue.PetID = int(parsed1)
		}
		raw2, present2, bindErr2 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr2 != nil {
			_ = writeRouteError(bindErr2)
			return
		}
		if present2 {
			requestValue.Language = string(raw2)
		}
		raw3, present3, bindErr3 := spiceweb.FormValue(formValues, "date", true)
		if bindErr3 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr3)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present3 {
			requestValue.Date = string(raw3)
		}
		raw4, present4, bindErr4 := spiceweb.FormValue(formValues, "description", true)
		if bindErr4 != nil {
			updatedBindingResult, rejectErr := bindingResult.RejectBinding(bindErr4)
			if rejectErr != nil {
				_ = writeRouteError(rejectErr)
				return
			}
			bindingResult = updatedBindingResult
		} else if present4 {
			requestValue.Description = string(raw4)
		}
		responseValue, routeErr := provider10.Create(httpRequest.Context(), requestValue, bindingResult)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation14, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route POST /owners/{ownerId}/pets/{petId}/visits/new: %w", routeErr))
	}
	routeObservation15, routeObservationErr15 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|57:github.com/StevenBuglione/spice/examples/petclinic/system|17:WelcomeController|4:Show", Module: "", Method: "GET", Pattern: "/"}, httpObservers...)
	if routeObservationErr15 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET / observation: %w", routeObservationErr15))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return provider1.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := system.WelcomeRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			requestValue.Language = string(raw0)
		}
		responseValue, routeErr := provider3.Show(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = provider1.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation15, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /: %w", routeErr))
	}
	application.hooks = []spicelifecycle.Hook{
		{
			ID:     "spice:symbol:v1|function|59:github.com/StevenBuglione/spice/examples/petclinic/postgres|0:|12:OpenDatabase",
			Module: "",
			Start:  provider5.Migrate,
		},
		{
			ID:     "spice:symbol:v1|function|63:github.com/StevenBuglione/spice/examples/petclinic/presentation|0:|9:NewServer",
			Module: "",
			Start:  provider14.Start,
			Stop:   provider14.Stop,
		},
	}
	managementChecks, err := spicemanagement.LifecycleChecks(TargetID, "github.com/StevenBuglione/spice/examples/petclinic/cmd/postgres", application.State)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management lifecycle checks: %w", err))
	}
	managementManager, err := spicemanagement.New(managementChecks...)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management checks: %w", err))
	}
	managementConfiguration, err := spicemanagement.NewConfigurationReport(configurationSchema, configurationSnapshot)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management configuration report: %w", err))
	}
	managementModules, err := spicemanagement.NewModuleReport(
		[]spicemanagement.ModuleDefinition{},
		[]spicemanagement.ModuleEdge{},
		[]string{},
	)
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management module report: %w", err))
	}
	managementHandler, err := spicemanagement.NewHandler(spicemanagement.HandlerOptions{
		Manager: managementManager,
		Info: map[string]string{
			"application": TargetID,
			"module":      "github.com/StevenBuglione/spice/examples/petclinic/cmd/postgres",
			"framework":   "Spice",
		},
		Metrics:       managementMetrics,
		Configuration: &managementConfiguration,
		Modules:       &managementModules,
		Expose: []spicemanagement.Endpoint{
			spicemanagement.EndpointConfigProps,
			spicemanagement.EndpointHealth,
			spicemanagement.EndpointInfo,
			spicemanagement.EndpointLiveness,
			spicemanagement.EndpointMetrics,
			spicemanagement.EndpointModules,
			spicemanagement.EndpointReadiness,
		},
	})
	if err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure management handler: %w", err))
	}
	if err := spiceweb.Register(routeMux, managementHandler.Pattern(), managementHandler); err != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register management routes: %w", err))
	}
	return application, nil
}

func (application *Application) State() spicelifecycle.State {
	if application == nil || application.coordinator == nil {
		return spicelifecycle.StateInvalid
	}
	return application.coordinator.State()
}

func (application *Application) Start(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("start application: application is nil")
	}
	return application.coordinator.Start(ctx, application.hooks)
}

func (application *Application) Stop(ctx context.Context) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("stop application: application is nil")
	}
	return application.coordinator.Stop(ctx)
}

func (application *Application) ShutdownTimeout() time.Duration {
	if application == nil {
		return 0
	}
	return application.shutdownTimeout
}

func (application *Application) RegisterObserver(observer spicelifecycle.Observer) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("register lifecycle observer: application is nil")
	}
	return application.coordinator.RegisterObserver(observer)
}

func (application *Application) Run(ctx context.Context, shutdown spicelifecycle.ContextFactory) error {
	if application == nil || application.coordinator == nil {
		return fmt.Errorf("run application: application is nil")
	}
	return application.coordinator.Run(ctx, application.hooks, shutdown)
}

// Components returns a typed snapshot of constructed singleton beans.
func (application *Application) Components() Components {
	if application == nil {
		return Components{}
	}
	return application.components
}

func (application *Application) Handler() http.Handler {
	if application == nil {
		return nil
	}
	return application.handler
}

type ShutdownContextFactory func(time.Duration) (context.Context, context.CancelFunc)

type CommandOptions struct {
	Context         context.Context
	Arguments       []string
	Stdout          io.Writer
	Stderr          io.Writer
	Logger          *slog.Logger
	ShutdownTimeout time.Duration
	ShutdownContext ShutdownContextFactory
	Application     ApplicationOptions
}

func Main(arguments []string) int {
	logger := slog.New(slog.NewJSONHandler(os.Stderr, nil))
	environment, err := spiceconfig.OSEnvironment("SPICE_")
	if err != nil {
		logger.Error("Spice command configuration failed", slog.Any("error", err))
		return ExitFailure
	}
	runContext, stopSignals := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stopSignals()
	return RunCommand(CommandOptions{
		Context:   runContext,
		Arguments: arguments,
		Stdout:    os.Stdout,
		Stderr:    os.Stderr,
		Logger:    logger,
		Application: ApplicationOptions{
			Sources: []spiceconfig.Source{environment},
		},
	})
}

func RunCommand(options CommandOptions) int {
	stdout := options.Stdout
	if stdout == nil {
		stdout = io.Discard
	}
	stderr := options.Stderr
	if stderr == nil {
		stderr = io.Discard
	}
	logger := options.Logger
	if logger == nil {
		logger = slog.New(slog.NewJSONHandler(stderr, nil))
	}
	ctx := options.Context
	if ctx == nil {
		return commandFailure(context.Background(), logger, "Spice command context is nil", nil)
	}
	if options.ShutdownTimeout < 0 {
		return commandFailure(ctx, logger, "Spice shutdown timeout is invalid", nil)
	}

	flags := flag.NewFlagSet(TargetID, flag.ContinueOnError)
	flags.SetOutput(stderr)
	check := flags.Bool("check", false, "construct the generated application and exit")
	if err := flags.Parse(options.Arguments); err != nil {
		logger.ErrorContext(ctx, "Spice command arguments are invalid", slog.Any("error", err))
		return ExitUsage
	}
	if flags.NArg() != 0 {
		if _, err := fmt.Fprintf(stderr, "%s does not accept positional arguments\n", TargetID); err != nil {
			logger.ErrorContext(ctx, "Spice command usage output failed", slog.Any("error", err))
		}
		return ExitUsage
	}

	applicationOptions := options.Application
	applicationOptions.Logger = logger
	logger.InfoContext(ctx, "Spice application constructing", slog.String("application", TargetID))
	application, err := NewApplicationWithOptions(ctx, applicationOptions)
	if err != nil {
		return commandFailure(ctx, logger, "Spice application construction failed", err)
	}

	shutdownTimeout := application.shutdownTimeout
	if options.ShutdownTimeout > 0 {
		shutdownTimeout = options.ShutdownTimeout
	}
	shutdownContext := options.ShutdownContext
	if shutdownContext == nil {
		shutdownContext = func(timeout time.Duration) (context.Context, context.CancelFunc) {
			return context.WithTimeout(context.Background(), timeout)
		}
	}
	shutdown := func() (context.Context, context.CancelFunc) {
		return shutdownContext(shutdownTimeout)
	}

	if *check {
		if err := stopCheckedApplication(application, shutdown); err != nil {
			return commandFailure(ctx, logger, "Spice application check cleanup failed", err)
		}
		if _, err := fmt.Fprintf(stdout, "Spice %s ready.\n", TargetID); err != nil {
			return commandFailure(ctx, logger, "Spice readiness output failed", err)
		}
		return ExitSuccess
	}

	logger.InfoContext(ctx, "Spice application starting", slog.String("application", TargetID))
	if err := application.Run(ctx, shutdown); err != nil {
		return commandFailure(ctx, logger, "Spice application run failed", err)
	}
	logger.InfoContext(context.Background(), "Spice application stopped", slog.String("application", TargetID))
	return ExitSuccess
}

func stopCheckedApplication(
	application *Application,
	shutdown spicelifecycle.ContextFactory,
) error {
	shutdownContext, cancel := shutdown()
	if shutdownContext == nil || cancel == nil {
		return fmt.Errorf("check application: shutdown context factory returned a nil context or cancel function")
	}
	defer cancel()
	return application.Stop(shutdownContext)
}

func commandFailure(
	ctx context.Context,
	logger *slog.Logger,
	message string,
	err error,
) int {
	if err == nil {
		logger.ErrorContext(ctx, message)
	} else {
		logger.ErrorContext(ctx, message, slog.Any("error", err))
	}
	return ExitFailure
}
