//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: cmd/mysql/main.go:18

package spicegen

// ApplicationTargetMysql_89cf8ad0 identifies the generated target selected by spice:symbol:v1|function|61:github.com/spice-framework/spice/examples/petclinic/cmd/mysql|0:|4:main.
const ApplicationTargetMysql_89cf8ad0 = "mysql"
