//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: cmd/mysql/main.go:18

package spicegen

// ApplicationTarget47bdf520c582 identifies the generated target selected by spice:symbol:v1|function|60:github.com/StevenBuglione/spice/examples/petclinic/cmd/mysql|0:|4:main.
const ApplicationTarget47bdf520c582 = "mysql"
