//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: cmd/mysql/main.go:18

package spicegen

// ApplicationTargetMysql_47bdf520 identifies the generated target selected by spice:symbol:v1|function|60:github.com/StevenBuglione/spice/examples/petclinic/cmd/mysql|0:|4:main.
const ApplicationTargetMysql_47bdf520 = "mysql"
