// Code generated by Spice. DO NOT EDIT.
// Source: examples/petclinic/memory/owner_repository.go:17
//go:build !spice_generate

package memory

import (
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
)

// spiceImplementsf1a2fa856981 verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|15:OwnerRepository.
var spiceImplementsf1a2fa856981 owner.Repository = *new(*OwnerRepository)
