// Code generated by Spice. DO NOT EDIT.
// Source: examples/petclinic/memory/pet_type_repository.go:16
//go:build !spice_generate

package memory

import (
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
)

// spiceImplements03415e64d85b verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|17:PetTypeRepository.
var spiceImplements03415e64d85b owner.PetTypeRepository = *new(*PetTypeRepository)
