//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.
// Source: memory/vet_repository.go:16

package memory

import (
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
)

// spiceImplementsf75617ef7566 verifies the explicit @Implements binding for spice:symbol:v1|type|57:github.com/StevenBuglione/spice/examples/petclinic/memory|0:|13:VetRepository.
var spiceImplementsf75617ef7566 vet.Repository = *new(*VetRepository)
