//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"

	spicelifecycle "github.com/spice-framework/spice/lifecycle"
)

func configureGeneratedLifecycle(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	dependencies *applicationDependencies,
) (*Application, error) {
	_ = ctx
	_ = options
	_ = dependencies
	application.hooks = []spicelifecycle.Hook{
		{
			ID:     "spice:symbol:v1|function|64:github.com/spice-framework/spice/examples/petclinic/presentation|0:|9:NewServer",
			Module: "",
			Start:  dependencies.server.Start,
			Stop:   dependencies.server.Stop,
		},
	}
	return application, nil
}
