//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/spice-framework/spice/config"
	owner "github.com/spice-framework/spice/examples/petclinic/owner"
	spiceintercept "github.com/spice-framework/spice/intercept"
	spiceview "github.com/spice-framework/spice/view"
	spiceweb "github.com/spice-framework/spice/web"
)

func registerGeneratedRouteOwnerControllerFind_2cd5c768(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	routeMux *http.ServeMux,
) (*Application, error) {
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|57:github.com/spice-framework/spice/examples/petclinic/owner|10:Controller|4:Find", Module: "", Method: "GET", Pattern: "/owners"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners observation: %w", routeObservationErr0))
	}
	routeTerminal := func(invocationContext context.Context, invocationRequest owner.FindOwnersRequest) (spiceview.Result, error) {
		return dependencies.ownerController.Find(invocationContext, invocationRequest)
	}
	routeInvocation, routeInterceptorErr := spiceintercept.Chain(
		routeTerminal,
		options.Interceptors.ControllerFind...,
	)
	if routeInterceptorErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("construct generated typed interceptors for route GET /owners: %w", routeInterceptorErr))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return dependencies.renderer.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.FindOwnersRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationQuery, "lastName", httpRequest.URL.Query()["lastName"], false)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			requestValue.LastName = string(raw0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationQuery, "page", httpRequest.URL.Query()["page"], false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			parsed1, parseErr1 := spiceweb.Integer(spiceweb.LocationQuery, "page", raw1, 0)
			if parseErr1 != nil {
				_ = writeRouteError(parseErr1)
				return
			}
			requestValue.Page = int(parsed1)
		}
		raw2, present2, bindErr2 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr2 != nil {
			_ = writeRouteError(bindErr2)
			return
		}
		if present2 {
			requestValue.Language = string(raw2)
		}
		responseValue, routeErr := routeInvocation(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = dependencies.renderer.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners: %w", routeErr))
	}
	return application, nil
}
