//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	slog "log/slog"
	http "net/http"
	time "time"

	spicebean "github.com/StevenBuglione/spice/bean"
	spiceconfig "github.com/StevenBuglione/spice/config"
	spiceentrypoint "github.com/StevenBuglione/spice/examples/petclinic/internal/spicegen/petclinic/sources/_root"
	memory "github.com/StevenBuglione/spice/examples/petclinic/memory"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	presentation "github.com/StevenBuglione/spice/examples/petclinic/presentation"
	system "github.com/StevenBuglione/spice/examples/petclinic/system"
	vet "github.com/StevenBuglione/spice/examples/petclinic/vet"
	i18n "github.com/StevenBuglione/spice/i18n"
	spicelifecycle "github.com/StevenBuglione/spice/lifecycle"
	spiceview "github.com/StevenBuglione/spice/view"
	spiceweb "github.com/StevenBuglione/spice/web"
)

const TargetID = spiceentrypoint.ApplicationTargetPetclinic_2898e5e7

const (
	ExitSuccess = 0
	ExitFailure = 1
	ExitUsage   = 2
)

// Components is a typed snapshot of constructed singleton beans.
// It performs no reflection or string-based lookup.
type Components struct {
	// PetclinicDatabase is bean "newPetclinicDatabase".
	PetclinicDatabase *memory.Database
	// Catalog is bean "newCatalog".
	Catalog *i18n.Catalog
	// Renderer is bean "newRenderer".
	Renderer *spiceview.Renderer
	// Mux is bean "newMux".
	Mux *http.ServeMux
	// VetRepository is bean "vetRepository".
	VetRepository *memory.VetRepository
	// VetController is bean "controller".
	VetController *vet.Controller
	// OwnerRepository is bean "ownerRepository".
	OwnerRepository *memory.OwnerRepository
	// OwnerController is bean "controller".
	OwnerController *owner.Controller
	// VisitController is bean "visitController".
	VisitController *owner.VisitController
	// PetTypeRepository is bean "petTypeRepository".
	PetTypeRepository *memory.PetTypeRepository
	// PetController is bean "petController".
	PetController *owner.PetController
	// WelcomeController is bean "welcomeController".
	WelcomeController *system.WelcomeController
	// ServerSettings is bean "ServerSettings".
	ServerSettings presentation.ServerSettings
	// Server is bean "newServer".
	Server *presentation.Server
}

// BeanOverrides provides compile-time-typed singleton replacements.
// Replacements use the normal generated cleanup and rollback path.
type BeanOverrides struct {
	// PetclinicDatabase replaces bean "newPetclinicDatabase".
	PetclinicDatabase spicebean.Override[*memory.Database]
	// Catalog replaces bean "newCatalog".
	Catalog spicebean.Override[*i18n.Catalog]
	// Renderer replaces bean "newRenderer".
	Renderer spicebean.Override[*spiceview.Renderer]
	// Mux replaces bean "newMux".
	Mux spicebean.Override[*http.ServeMux]
	// VetRepository replaces bean "vetRepository".
	VetRepository spicebean.Override[*memory.VetRepository]
	// VetController replaces bean "controller".
	VetController spicebean.Override[*vet.Controller]
	// OwnerRepository replaces bean "ownerRepository".
	OwnerRepository spicebean.Override[*memory.OwnerRepository]
	// OwnerController replaces bean "controller".
	OwnerController spicebean.Override[*owner.Controller]
	// VisitController replaces bean "visitController".
	VisitController spicebean.Override[*owner.VisitController]
	// PetTypeRepository replaces bean "petTypeRepository".
	PetTypeRepository spicebean.Override[*memory.PetTypeRepository]
	// PetController replaces bean "petController".
	PetController spicebean.Override[*owner.PetController]
	// WelcomeController replaces bean "welcomeController".
	WelcomeController spicebean.Override[*system.WelcomeController]
	// Server replaces bean "newServer".
	Server spicebean.Override[*presentation.Server]
}

type Application struct {
	coordinator     *spicelifecycle.Coordinator
	hooks           []spicelifecycle.Hook
	shutdownTimeout time.Duration
	components      Components
	mux             *http.ServeMux
	handler         http.Handler
}

type ApplicationOptions struct {
	Overrides                 BeanOverrides
	Profiles                  []string
	Sources                   []spiceconfig.Source
	AllowUnknownConfiguration bool
	ErrorMapper               spiceweb.ErrorMapper
	MaxRequestBodyBytes       int64
	HTTPObservers             []spiceweb.HTTPObserver
	Middleware                []spiceweb.Middleware
	Logger                    *slog.Logger
	Observers                 []spicelifecycle.Observer
}
