//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	context "context"
	fmt "fmt"
	http "net/http"

	spiceconfig "github.com/StevenBuglione/spice/config"
	owner "github.com/StevenBuglione/spice/examples/petclinic/owner"
	spiceview "github.com/StevenBuglione/spice/view"
	spiceweb "github.com/StevenBuglione/spice/web"
)

func registerGeneratedRouteOwnerControllerEditForm_7455f8a2(
	ctx context.Context,
	application *Application,
	options ApplicationOptions,
	configurationSnapshot spiceconfig.Snapshot,
	dependencies *applicationDependencies,
	httpObservers []spiceweb.HTTPObserver,
	routeMux *http.ServeMux,
) (*Application, error) {
	_ = configurationSnapshot
	_ = dependencies
	_ = httpObservers
	routeObservation0, routeObservationErr0 := spiceweb.ObservationMiddleware(spiceweb.RouteMetadata{ID: "spice:symbol:v1|method|56:github.com/StevenBuglione/spice/examples/petclinic/owner|10:Controller|8:EditForm", Module: "", Method: "GET", Pattern: "/owners/{ownerId}/edit"}, httpObservers...)
	if routeObservationErr0 != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("configure generated route GET /owners/{ownerId}/edit observation: %w", routeObservationErr0))
	}
	if routeErr := spiceweb.RegisterObserved(routeMux, "GET /owners/{ownerId}/edit", http.HandlerFunc(func(writer http.ResponseWriter, httpRequest *http.Request) {
		writeRouteError := func(routeError error) error {
			return dependencies.renderer.WriteError(writer, httpRequest, routeError, options.ErrorMapper)
		}
		if !spiceview.AcceptsHTML(httpRequest.Header.Get("Accept")) {
			problem := spiceweb.Problem{
				Type:   "about:blank",
				Title:  "Not Acceptable",
				Status: http.StatusNotAcceptable,
				Detail: "the endpoint produces text/html",
			}
			_ = spiceweb.WriteProblem(writer, problem)
			return
		}
		requestValue := owner.OwnerIDRequest{}
		raw0, present0, bindErr0 := spiceweb.Parameter(spiceweb.LocationPath, "ownerId", []string{httpRequest.PathValue("ownerId")}, true)
		if bindErr0 != nil {
			_ = writeRouteError(bindErr0)
			return
		}
		if present0 {
			parsed0, parseErr0 := spiceweb.Integer(spiceweb.LocationPath, "ownerId", raw0, 0)
			if parseErr0 != nil {
				_ = writeRouteError(parseErr0)
				return
			}
			requestValue.OwnerID = int(parsed0)
		}
		raw1, present1, bindErr1 := spiceweb.Parameter(spiceweb.LocationHeader, "Accept-Language", httpRequest.Header.Values("Accept-Language"), false)
		if bindErr1 != nil {
			_ = writeRouteError(bindErr1)
			return
		}
		if present1 {
			requestValue.Language = string(raw1)
		}
		responseValue, routeErr := dependencies.ownerController.EditForm(httpRequest.Context(), requestValue)
		if routeErr != nil {
			_ = writeRouteError(routeErr)
			return
		}
		_ = dependencies.renderer.Respond(httpRequest.Context(), writer, responseValue)
	}), routeObservation0, options.Middleware...); routeErr != nil {
		return nil, application.coordinator.Abort(ctx, fmt.Errorf("register generated route GET /owners/{ownerId}/edit: %w", routeErr))
	}
	return application, nil
}
