//go:build !spice_generate

// Code generated by Spice. DO NOT EDIT.

package spicegen

import (
	spiceconfig "github.com/spice-framework/spice/config"
)

func ConfigurationSchema() (spiceconfig.Schema, error) {
	return spiceconfig.NewSchema(
		spiceconfig.Property{
			Key:         "petclinic.server.address",
			Kind:        spiceconfig.KindString,
			Environment: "SPICE_PETCLINIC_ADDRESS",
			Default:     "127.0.0.1:8080",
			HasDefault:  true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.read-header-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "5s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.read-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "15s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.write-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "15s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:        "petclinic.server.idle-timeout",
			Kind:       spiceconfig.KindDuration,
			Default:    "60s",
			HasDefault: true,
		},
		spiceconfig.Property{
			Key:         "spice.shutdown-timeout",
			Kind:        spiceconfig.KindDuration,
			Environment: "SPICE_SHUTDOWN_TIMEOUT",
			Default:     "10s",
			HasDefault:  true,
		},
	)
}
